import { type DeleteItemNet, type MoveItemNet, type ZoneSessionNet } from "./generated/net-structs.js";
import type { PersistCharacter } from "../persist/types.js";
export type ZoneRouteRequest = ZoneSessionNet;
export type MoveItemRequest = MoveItemNet;
export type DeleteItemRequest = DeleteItemNet;
export declare function decodeJwtLoginToken(payload: Uint8Array): string;
export declare function decodeCharacterCreateName(payload: Uint8Array): string;
export declare function decodeCharacterCreate(payload: Uint8Array): Record<string, unknown> | null;
export declare function decodeCharacterDeleteName(payload: Uint8Array): string;
export declare function decodeEnterWorldName(payload: Uint8Array): string;
export declare function decodeZoneRouteRequest(payload: Uint8Array): ZoneRouteRequest;
export declare function decodeMoveItemRequest(payload: Uint8Array): MoveItemRequest | null;
export declare function encodeMoveItemResponse(value: MoveItemRequest): Uint8Array;
export declare function decodeDeleteItemRequest(payload: Uint8Array): DeleteItemRequest | null;
export declare function encodeJwtResponse(status: number): Uint8Array;
export declare function encodeIntValue(value: number): Uint8Array;
export declare function encodeCharacterSelect(characters: PersistCharacter[]): Uint8Array;
export declare function encodeInteger(value: number): Uint8Array;
export declare function encodeNewZone(value: Record<string, unknown>): Uint8Array;
export declare function encodePlayerProfile(value: Record<string, unknown>): Uint8Array;
export declare function encodeZoneSpawns(value: Record<string, unknown>): Uint8Array;
export declare function encodeZoneSpawn(value: Record<string, unknown>): Uint8Array;
export declare function encodeDeleteSpawn(value: Record<string, unknown>): Uint8Array;
export declare function encodeChannelMessage(value: Record<string, unknown>): Uint8Array;
