export declare const OP: {
    readonly JWT_RESPONSE: 3;
    readonly JWT_LOGIN: 4;
    readonly CHARACTER_CREATE: 11;
    readonly DELETE_CHARACTER: 12;
    readonly APPROVE_NAME_SERVER: 13;
    readonly ENTER_WORLD: 14;
    readonly POST_ENTER_WORLD: 17;
    readonly SEND_CHAR_INFO: 18;
    readonly ZONE_SESSION: 25;
    readonly ZONE_SESSION_VALID: 26;
    readonly DELETE_SPAWN: 85;
    readonly ZONE_SPAWNS: 238;
    readonly BATCH_ZONE_SPAWNS: 239;
    readonly NEW_ZONE: 285;
    readonly PLAYER_PROFILE: 287;
    readonly CLIENT_UPDATE: 41;
    readonly CAMP: 76;
    readonly MOVE_ITEM: 75;
    readonly CHANNEL_MESSAGE: 82;
    readonly GM_COMMAND: 83;
    readonly DELETE_ITEM: 112;
    readonly BULK_DELETE_ITEMS: 113;
    readonly ITEM_PACKET: 230;
    readonly ADD_ITEM_PACKET: 231;
    readonly ANIMATION: 253;
    readonly LEVEL_UPDATE: 275;
    readonly REQUEST_CLIENT_ZONE_CHANGE: 291;
    readonly RENDER_SNAPSHOT: 560;
};
export type KnownOpcode = (typeof OP)[keyof typeof OP];
export declare const WORLD_GLOBAL_OPCODES: Set<number>;
export declare const ZONE_HANDLED_OPCODES: Set<number>;
