export const OP = {
  JWT_RESPONSE: 3,
  JWT_LOGIN: 4,
  CHARACTER_CREATE: 11,
  DELETE_CHARACTER: 12,
  APPROVE_NAME_SERVER: 13,
  ENTER_WORLD: 14,
  POST_ENTER_WORLD: 17,
  SEND_CHAR_INFO: 18,
  ZONE_SESSION: 25,
  ZONE_SESSION_VALID: 26,
  DELETE_SPAWN: 85,
  ZONE_SPAWNS: 238,
  BATCH_ZONE_SPAWNS: 239,
  NEW_ZONE: 285,
  PLAYER_PROFILE: 287,

  CLIENT_UPDATE: 41,
  CAMP: 76,
  MOVE_ITEM: 75,
  CHANNEL_MESSAGE: 82,
  GM_COMMAND: 83,
  DELETE_ITEM: 112,
  BULK_DELETE_ITEMS: 113,
  ITEM_PACKET: 230,
  ADD_ITEM_PACKET: 231,
  ANIMATION: 253,
  LEVEL_UPDATE: 275,
  REQUEST_CLIENT_ZONE_CHANGE: 291,
  RENDER_SNAPSHOT: 560,
} as const;

export type KnownOpcode = (typeof OP)[keyof typeof OP];

export const WORLD_GLOBAL_OPCODES = new Set<number>([
  OP.JWT_LOGIN,
  OP.CHARACTER_CREATE,
  OP.DELETE_CHARACTER,
  OP.ENTER_WORLD,
  OP.ZONE_SESSION,
  OP.REQUEST_CLIENT_ZONE_CHANGE,
]);

export const ZONE_HANDLED_OPCODES = new Set<number>([
  OP.REQUEST_CLIENT_ZONE_CHANGE,
  OP.CHANNEL_MESSAGE,
  OP.CLIENT_UPDATE,
  OP.ANIMATION,
  OP.CAMP,
  OP.MOVE_ITEM,
  OP.DELETE_ITEM,
  OP.GM_COMMAND,
]);
