import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const serverPath = resolve(import.meta.dirname, "../src/protocol/generated/net-structs.ts");
const clientPath = resolve(import.meta.dirname, "../../client/src/Game/Net/generated/net-structs.ts");
const [serverSource, clientSource] = await Promise.all([
  readFile(serverPath, "utf8"),
  readFile(clientPath, "utf8"),
]);
const [installedPackage, workspacePackage] = await Promise.all([
  readFile(resolve(import.meta.dirname, "../node_modules/shader-object/package.json"), "utf8"),
  readFile(resolve(import.meta.dirname, "../../shader-object/package.json"), "utf8"),
]);
const installedVersion = (JSON.parse(installedPackage) as { version: string }).version;
const workspaceVersion = (JSON.parse(workspacePackage) as { version: string }).version;
if (installedVersion !== workspaceVersion) {
  throw new Error(
    `ServerJS resolves shader-object ${installedVersion}, workspace is ${workspaceVersion}; run npm install`,
  );
}

if (serverSource !== clientSource) {
  throw new Error("Client and ServerJS Shado net bindings differ; run npm run net:generate");
}
if (!serverSource.startsWith("// Generated by Shado")) {
  throw new Error("Net bindings are not marked as Shado-generated output");
}
console.log(
  `Client and ServerJS Shado net bindings are byte-identical (shader-object ${installedVersion})`,
);
