import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { emitNetStructModule } from "shader-object";
import { netStructs } from "./net-structs.schema.js";

const output = resolve(
  import.meta.dirname,
  "../src/protocol/generated/net-structs.ts",
);
const source = emitNetStructModule(netStructs, {
  banner:
    "// Generated by Shado from scripts/net-structs.schema.ts. Do not edit.",
});

await writeFile(output, source, "utf8");
const clientOutput = resolve(
  import.meta.dirname,
  "../../client/src/Game/Net/generated/net-structs.ts",
);
await writeFile(clientOutput, source, "utf8");
console.log(`Generated ${output}`);
console.log(`Generated ${clientOutput}`);
