import type * as BJS from "@babylonjs/core";
import BABYLON from "@bjs";
import { RaceEntry } from "@game/Constants/race-data";
import type GameManager from "@game/Manager/game-manager";
import { PlayerProfile, Spawn } from "@game/Net/messages";
import { NullableItemInstance } from "@game/Player/player-constants";
import EntityCache, { type EntityContainer } from "./entity-cache";
import type { RequiemEntityActor } from "./shado-entity-pool";
type InstanceContainer = {
    mesh: BJS.Mesh;
    thinInstanceIndex: number;
    actor: RequiemEntityActor;
};
export declare class Entity extends BABYLON.TransformNode {
    spawn: Spawn | PlayerProfile;
    entityContainer: EntityContainer;
    entityCache: typeof EntityCache;
    spawnPosition: BJS.Vector3;
    spawnScale: number;
    hidden: boolean;
    raceDataEntry: RaceEntry | null;
    get cleanName(): string;
    private static targetRing;
    private static currentlySelected;
    private static targetTexture;
    static disposeStatics(): void;
    static instantiateStatics(scene: BJS.Scene): void;
    private gameManager;
    private scene;
    private animationBuffer;
    meshInstance: InstanceContainer | null;
    nameplateLines: string[];
    private capsuleShape;
    private pickInst;
    private isPlayer;
    private disposed;
    private appearanceGeneration;
    private visibilityOverride;
    private readonly itemResolver?;
    readonly ready: Promise<void>;
    get lifecycleDisposed(): boolean;
    get isPlayerRace(): boolean;
    private get physicsPlugin();
    constructor(gameManager: GameManager, spawn: Spawn | PlayerProfile, scene: BJS.Scene, entityContainer: EntityContainer, entityCache: typeof EntityCache, parent: BJS.Node, raceEntry: RaceEntry, itemResolver?: (slot: number) => NullableItemInstance);
    private setup;
    get isHumanoid(): boolean;
    /** Playable races select facial variants by the profile face field. Classic
     * city NPC models are humanoid for armor, but encode heads as materials. */
    private get usesPlayerFaceTextures();
    getHeading(): number;
    setVelocity(x: number, y: number, z: number): void;
    private lastYaw;
    setRotation(yaw: number): void;
    setPosition(x: number, y: number, z: number): void;
    getClosestSpawns(n?: number, filter?: (spawn: Entity) => boolean): Entity[];
    setSelected(selected: boolean, color?: BJS.Color4): void;
    dispose(): void;
    toggleVisibility(visible: boolean): void;
    hide(): Promise<void>;
    initialize(): Promise<void>;
    applyReducedVisibility(): void;
    private updateMaterialBuffers;
    private instantiateMeshes;
    private isNpc;
    private isPc;
    private headModel;
    private robeModel;
    private primaryMeshes;
    private secondaryMeshes;
    private appearanceUpdate;
    private updatePrimary;
    private createParticleEffects;
    private updateSecondary;
    updateModelTextures(): Promise<void>;
    private updateModelTexturesNow;
    private equippedItem;
    private setupPhysics;
    instantiateNameplate(textLines: string[]): Promise<void>;
    private lastPosition;
    private lastRotationQuaternion;
    syncMatrix(): void;
    checkBelowAndReposition(): void;
    setFace(variation: number): void;
    currentAnimation: string | null;
    animationTimeout: NodeJS.Timeout | boolean;
    queuedAnimation: string | null;
    private computeOffset;
    playAnimation(name: string, playThrough?: boolean): void;
    private getTextureIndex;
    private getTextureIndexImpl;
}
export {};
