// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: world/world.proto

package world

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JWTLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTLogin) Reset() {
	*x = JWTLogin{}
	mi := &file_world_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTLogin) ProtoMessage() {}

func (x *JWTLogin) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTLogin.ProtoReflect.Descriptor instead.
func (*JWTLogin) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{0}
}

func (x *JWTLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JWTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTResponse) Reset() {
	*x = JWTResponse{}
	mi := &file_world_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTResponse) ProtoMessage() {}

func (x *JWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTResponse.ProtoReflect.Descriptor instead.
func (*JWTResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{1}
}

func (x *JWTResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type WebInitiateConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         bool                   `protobuf:"varint,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebInitiateConnection) Reset() {
	*x = WebInitiateConnection{}
	mi := &file_world_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebInitiateConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebInitiateConnection) ProtoMessage() {}

func (x *WebInitiateConnection) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebInitiateConnection.ProtoReflect.Descriptor instead.
func (*WebInitiateConnection) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{2}
}

func (x *WebInitiateConnection) GetLogin() bool {
	if x != nil {
		return x.Login
	}
	return false
}

var File_world_world_proto protoreflect.FileDescriptor

const file_world_world_proto_rawDesc = "" +
	"\n" +
	"\x11world/world.proto\x12\beq.world\" \n" +
	"\bJWTLogin\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"%\n" +
	"\vJWTResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"-\n" +
	"\x15WebInitiateConnection\x12\x14\n" +
	"\x05login\x18\x01 \x01(\bR\x05loginB(Z&knervous/eqgo/internal/api/proto/worldb\x06proto3"

var (
	file_world_world_proto_rawDescOnce sync.Once
	file_world_world_proto_rawDescData []byte
)

func file_world_world_proto_rawDescGZIP() []byte {
	file_world_world_proto_rawDescOnce.Do(func() {
		file_world_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_world_world_proto_rawDesc), len(file_world_world_proto_rawDesc)))
	})
	return file_world_world_proto_rawDescData
}

var file_world_world_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_world_world_proto_goTypes = []any{
	(*JWTLogin)(nil),              // 0: eq.world.JWTLogin
	(*JWTResponse)(nil),           // 1: eq.world.JWTResponse
	(*WebInitiateConnection)(nil), // 2: eq.world.WebInitiateConnection
}
var file_world_world_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_world_world_proto_init() }
func file_world_world_proto_init() {
	if File_world_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_world_proto_rawDesc), len(file_world_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_world_world_proto_goTypes,
		DependencyIndexes: file_world_world_proto_depIdxs,
		MessageInfos:      file_world_world_proto_msgTypes,
	}.Build()
	File_world_world_proto = out.File
	file_world_world_proto_goTypes = nil
	file_world_world_proto_depIdxs = nil
}
