export declare const charFileRegex: RegExp;
export declare const clkRegex: RegExp;
export declare const pcModels: string[];
export declare const isPlayerRace: (model: string) => boolean;
export declare const humanoidNpcRaces: Set<number>;
export declare const MaterialPrefixes: {
    Face: string;
    Chest: string;
    Arms: string;
    Wrists: string;
    Legs: string;
    Hands: string;
    Feet: string;
    Helm: string;
};
export declare const VIEWS: {
    CHAR_SELECT: number;
    CHAR_CREATE: number;
};
export declare const Races: {
    HUMAN: number;
    BARBARIAN: number;
    ERUDITE: number;
    WOODELF: number;
    HIGHELF: number;
    DARKELF: number;
    HALFELF: number;
    DWARF: number;
    TROLL: number;
    OGRE: number;
    HALFLING: number;
    GNOME: number;
    AVIAK: number;
    WEREWOLF: number;
};
export declare const AbbreviatedRaces: {
    HUM: number;
    BAR: number;
    ERU: number;
    ELF: number;
    HIE: number;
    DEF: number;
    HEF: number;
    DWF: number;
    TRL: number;
    OGR: number;
    HLF: number;
    GNM: number;
};
export declare const Classes: {
    WAR: number;
    CLR: number;
    PAL: number;
    RNG: number;
    SHD: number;
    DRU: number;
    MNK: number;
    BRD: number;
    ROG: number;
    SHM: number;
    NEC: number;
    WIZ: number;
    MAG: number;
    ENC: number;
    BST: number;
    BER: number;
};
export declare const StartingZones: {
    SouthQeynos: (string | number)[];
    NorthQeynos: (string | number)[];
    SurefallGlade: (string | number)[];
    NorthFreeport: (string | number)[];
    WestFreeport: (string | number)[];
    EastFreeport: (string | number)[];
    GreaterFaydark: (string | number)[];
    Halas: (string | number)[];
    Oggok: (string | number)[];
    Grobb: (string | number)[];
    NorthKaladim: (string | number)[];
    SouthKaladim: (string | number)[];
    Paineel: (string | number)[];
    Erudin: (string | number)[];
    ErudinPalace: (string | number)[];
    AkAnon: (string | number)[];
    Rivervale: (string | number)[];
    NorthernFelwithe: (string | number)[];
    SouthernFelwithe: (string | number)[];
    QeynosAqueducts: (string | number)[];
    NeriakCommons: (string | number)[];
    NeriakThirdGate: (string | number)[];
};
export declare const CharRaceStrings: {
    [Races.HUMAN]: number;
    [Races.BARBARIAN]: number;
    [Races.ERUDITE]: number;
    [Races.WOODELF]: number;
    [Races.HIGHELF]: number;
    [Races.DARKELF]: number;
    [Races.HALFELF]: number;
    [Races.DWARF]: number;
    [Races.TROLL]: number;
    [Races.OGRE]: number;
    [Races.HALFLING]: number;
    [Races.GNOME]: number;
    [Races.AVIAK]: number;
    [Races.WEREWOLF]: number;
};
export declare const CharClassStrings: {
    [Classes.WAR]: number;
    [Classes.CLR]: number;
    [Classes.PAL]: number;
    [Classes.RNG]: number;
    [Classes.SHD]: number;
    [Classes.DRU]: number;
    [Classes.MNK]: number;
    [Classes.BRD]: number;
    [Classes.ROG]: number;
    [Classes.SHM]: number;
    [Classes.NEC]: number;
    [Classes.WIZ]: number;
    [Classes.MAG]: number;
    [Classes.ENC]: number;
};
export declare const Deity: {
    Unknown: (string | number)[];
    Agnostic_LB: (string | number)[];
    Bertoxxulous: (string | number)[];
    BrellSerilis: (string | number)[];
    CazicThule: (string | number)[];
    ErollisiMarr: (string | number)[];
    Bristlebane: (string | number)[];
    Innoruuk: (string | number)[];
    Karana: (string | number)[];
    MithanielMarr: (string | number)[];
    Prexus: (string | number)[];
    Quellious: (string | number)[];
    RallosZek: (string | number)[];
    RodcetNife: (string | number)[];
    SolusekRo: (string | number)[];
    TheTribunal: (string | number)[];
    Tunare: (string | number)[];
    Veeshan: (string | number)[];
    Agnostic: (string | number)[];
};
export declare const preferredStats: {
    1: string[];
    2: string[];
    3: string[];
    4: string[];
    5: string[];
    6: string[];
    7: string[];
    8: string[];
    9: string[];
    10: string[];
    11: string[];
    12: string[];
    13: string[];
    14: string[];
};
export declare const baseStats: number[][];
export declare const baseClassStats: number[][];
export declare const classLookupTable: boolean[][];
