export declare enum Skills {
    OneHandedBlunt = 0,
    OneHandedSlashing = 1,
    TwoHandedBlunt = 2,
    TwoHandedSlashing = 3,
    Abjuration = 4,
    Alteration = 5,// 5
    ApplyPoison = 6,
    Archery = 7,
    Backstab = 8,
    BindWound = 9,
    Bash = 10,// 10
    Block = 11,
    BrassInstruments = 12,
    Channeling = 13,
    Conjuration = 14,
    Defense = 15,// 15
    Disarm = 16,
    DisarmTraps = 17,
    Divination = 18,
    Dodge = 19,
    DoubleAttack = 20,// 20
    DragonPunchTailRake = 21,// Dragon Punch is the Iksar Monk skill Tail Rake is the Iksar Monk equivalent
    DualWield = 22,
    EagleStrike = 23,
    Evocation = 24,
    FeignDeath = 25,// 25
    FlyingKick = 26,
    Forage = 27,
    HandToHand = 28,
    Hide = 29,
    Kick = 30,// 30
    Meditate = 31,
    Mend = 32,
    Offense = 33,
    Parry = 34,
    PickLock = 35,// 35
    OneHandedPiercing = 36,// Changed in RoF2(05-10-2
    Riposte = 37,
    RoundKick = 38,
    SafeFall = 39,
    SenseHeading = 40,// 40
    Singing = 41,
    Sneak = 42,
    SpecializeAbjure = 43,// No idea why they trunca
    SpecializeAlteration = 44,
    SpecializeConjuration = 45,// 45
    SpecializeDivination = 46,
    SpecializeEvocation = 47,
    PickPockets = 48,
    StringedInstruments = 49,
    Swimming = 50,// 50
    Throwing = 51,
    TigerClaw = 52,
    Tracking = 53,
    WindInstruments = 54,
    Fishing = 55,// 55
    MakePoison = 56,
    Tinkering = 57,
    Research = 58,
    Alchemy = 59,
    Baking = 60,// 60
    Tailoring = 61,
    SenseTraps = 62,
    Blacksmithing = 63,
    Fletching = 64,
    Brewing = 65,// 65
    AlcoholTolerance = 66,
    Begging = 67,
    JewelryMaking = 68,
    Pottery = 69,
    PercussionInstruments = 70,// 70
    Intimidation = 71,
    Berserking = 72,
    Taunt = 73,
    Frenzy = 74,// 74
    RemoveTraps = 75,// 75
    TripleAttack = 76,
    TwoHandedPiercing = 77
}
export declare const ActiveCombatSkills: Skills[];
