import type * as BJS from "@babylonjs/core";
import { LightManager } from "@game/Lights/light-manager";
import type GameManager from "@game/Manager/game-manager";
import { Spawns } from "@game/Net/messages";
import { RegionManager } from "@game/Regions/region-manager";
import DayNightSkyManager from "@game/Sky/sky-manager";
import EntityPool from "./entity-pool";
import { Grid } from "./zone-grid";
export declare class ZoneManager {
    get RegionManager(): RegionManager;
    get LightManager(): LightManager;
    private lightManager;
    get SkyManager(): DayNightSkyManager;
    private skyManager;
    private regionManager;
    get ZoneContainer(): BJS.TransformNode | null;
    private zoneContainer;
    private objectContainer;
    private lightContainer;
    private entityContainerNode;
    grid: Grid | null;
    private tickObservable;
    get EntityPool(): EntityPool | null;
    private entityPool;
    private zoneObjects;
    private shadoWorldObjects;
    private disableWorldEnv;
    zoneName: string;
    get CurrentZone(): import("@game/Net/messages").NewZone | null;
    get GameManager(): GameManager;
    private parent;
    private animatedTextures;
    private worldTickElapsedMs;
    private loadGeneration;
    constructor(parent: GameManager);
    dispose(destroy?: boolean): void;
    loadZone(zoneName: string): Promise<void>;
    loadSpawns(spawns: Spawns): Promise<void>;
    private cleanupUnusedMaterials;
    instantiateZone(generation?: number): Promise<void>;
    private dedupeMaterialsByName;
    private instantiateObjects;
    private instantiatePromotedObjects;
    tick(): void;
}
