import type { DatabaseRow } from "../db/backend.js";
export interface GameItemRow extends DatabaseRow {
    id: number;
    name: string;
    idfile: string;
    icon: number;
    material: number;
    color: number;
    itemtype: number;
    slots: number;
    ac: number;
    bagslots: number;
    classes: number;
    races: number;
    stackable: number;
    stacksize: number;
    maxcharges: number;
    weight: number;
    damage: number;
    delay: number;
    astr: number;
    asta: number;
    adex: number;
    aagi: number;
    aint: number;
    awis: number;
    acha: number;
    hp: number;
    mana: number;
    dr: number;
    mr: number;
    cr: number;
    fr: number;
    pr: number;
    haste: number;
    magic: number;
    nodrop: number;
}
/** One item wire projection shared by offline and network backends. */
export declare function toItemInstance(item: Partial<GameItemRow> & Pick<GameItemRow, "id" | "name">, slot: number, bagSlot: number, quantity?: number): Record<string, unknown>;
