export const CLASS_DATA_NAMES = { 
  1: "Warrior",
  2: "Cleric",
  3: "Paladin",
  4: "Ranger",
  5: "Shadowknight",
  6: "Druid",
  7: "Monk",
  8: "Bard",
  9: "Rogue",
  10: "Shaman",
  11: "Necromancer",
  12: "Wizard",
  13: "Mage",
  14: "Enchanter",
  15: "Beastlord",
  16: "Berserker",
  20: "Warrior GM",
  21: "Cleric GM",
  22: "Paladin GM",
  23: "Ranger GM",
  24: "Shadowknight GM",
  25: "Druid GM",
  26: "Monk GM",
  27: "Bard GM",
  28: "Rogue GM",
  29: "Shaman GM",
  30: "Necromancer GM",
  31: "Wizard GM",
  32: "Mage GM",
  33: "Enchanter GM",
  41: "Merchant",
  40: "Banker",
  60: "LDON Recruiter",
  61: "LDON Merchant",
  63: "Tribute Master",
};


export const CLASS_DATA_ENUM = {
  "Warrior": 1,
  "Cleric": 2,
  "Paladin": 3,
  "Ranger": 4,
  "Shadowknight": 5,
  "Druid": 6,
  "Monk": 7,
  "Bard": 8,
  "Rogue": 9,
  "Shaman": 10,
  "Necromancer": 11,
  "Wizard": 12,
  "Mage": 13,
  "Enchanter": 14,
  "Beastlord": 15,
  "Berserker": 16,
  "WarriorGM": 20,
  "ClericGM": 21,
  "PaladinGM": 22,
  "RangerGM": 23,
  "ShadowknightGM": 24,
  "DruidGM": 25,
  "MonkGM": 26,
  "BardGM": 27,
  "RogueGM": 28,
  "ShamanGM": 29,
  "NecromancerGM": 30,
  "WizardGM": 31,
  "MageGM": 32,
  "EnchanterGM": 33,
  "Merchant": 41,
  "Banker": 40,
  "LDONRecruiter": 60,
  "LDONMerchant": 61,
  "TributeMaster": 63,
};