import { BaseCommandHandler } from './command-base';
export declare function requestZoneByShortName(rawZone?: string): void;
export declare class CommandHandler extends BaseCommandHandler {
    private setMode;
    setModeHandler(setMode: React.Dispatch<React.SetStateAction<string>>): void;
    commandSpeed(args: string[]): void;
    commandSit(): void;
    commandWalk(): void;
    commandHelp(): void;
    commandLocation(): void;
    commandControls(): void;
    commandTarget(args: string[]): void;
    commandListZones(): void;
    commandZone(args: string[]): void;
    commandWho(): void;
    commandInvite(args: string[]): void;
    commandDisband(): void;
    commandOptions(): void;
    commandPersona(): void;
    commandSay(args: string[]): void;
    commandCamp(): void;
    commandNod(): void;
    commandAmaze(): void;
    commandPlead(): void;
    commandClap(): void;
    commandHungry(): void;
    commandBlush(): void;
    commandChuckle(): void;
    commandCough(): void;
    commandDuck(): void;
    commandPuzzle(): void;
    commandDance(): void;
    commandBlink(): void;
    commandGlare(): void;
    commandDrool(): void;
    commandKneel(): void;
    commandLaugh(): void;
    commandPoint(): void;
    commandShrug(): void;
    commandReady(): void;
    commandSalute(): void;
    commandShiver(): void;
    commandTap(): void;
    commandBow(): void;
    commandWave(): void;
    commandCheer(): void;
    commandRude(): void;
    commandHail(): void;
    commandConsider(): void;
    commandGoto(args: string[]): void;
}
