// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "common/opcodes.proto" (package "eq.common", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum eq.common.OpCodes
 */
export enum OpCodes {
    /**
     * @generated from protobuf enum value: OP_Unknown = 0;
     */
    OP_Unknown = 0,
    /**
     * JWT
     *
     * @generated from protobuf enum value: OP_JWTLogin = 10;
     */
    OP_JWTLogin = 10,
    /**
     * @generated from protobuf enum value: OP_JWTResponse = 11;
     */
    OP_JWTResponse = 11,
    /**
     * Login
     *
     * @generated from protobuf enum value: OP_LoginAccepted = 12;
     */
    OP_LoginAccepted = 12,
    /**
     * @generated from protobuf enum value: OP_PlayEverquestRequest = 13;
     */
    OP_PlayEverquestRequest = 13,
    /**
     * @generated from protobuf enum value: OP_PlayEverquestResponse = 14;
     */
    OP_PlayEverquestResponse = 14,
    /**
     * @generated from protobuf enum value: OP_ServerListRequest = 15;
     */
    OP_ServerListRequest = 15,
    /**
     * @generated from protobuf enum value: OP_ServerListResponse = 16;
     */
    OP_ServerListResponse = 16,
    /**
     * World
     *
     * @generated from protobuf enum value: OP_ApproveName = 17;
     */
    OP_ApproveName = 17,
    /**
     * @generated from protobuf enum value: OP_CharacterCreate = 18;
     */
    OP_CharacterCreate = 18,
    /**
     * @generated from protobuf enum value: OP_DeleteCharacter = 19;
     */
    OP_DeleteCharacter = 19,
    /**
     * @generated from protobuf enum value: OP_ApproveName_Server = 20;
     */
    OP_ApproveName_Server = 20,
    /**
     * @generated from protobuf enum value: OP_EnterWorld = 21;
     */
    OP_EnterWorld = 21,
    /**
     * @generated from protobuf enum value: OP_ExpansionInfo = 22;
     */
    OP_ExpansionInfo = 22,
    /**
     * @generated from protobuf enum value: OP_GuildsList = 23;
     */
    OP_GuildsList = 23,
    /**
     * @generated from protobuf enum value: OP_PostEnterWorld = 24;
     */
    OP_PostEnterWorld = 24,
    /**
     * @generated from protobuf enum value: OP_SendCharInfo = 25;
     */
    OP_SendCharInfo = 25,
    /**
     * @generated from protobuf enum value: OP_SendLoginInfo = 26;
     */
    OP_SendLoginInfo = 26,
    /**
     * @generated from protobuf enum value: OP_SendMaxCharacters = 27;
     */
    OP_SendMaxCharacters = 27,
    /**
     * @generated from protobuf enum value: OP_SendMembership = 28;
     */
    OP_SendMembership = 28,
    /**
     * @generated from protobuf enum value: OP_SendMembershipDetails = 29;
     */
    OP_SendMembershipDetails = 29,
    /**
     * @generated from protobuf enum value: OP_ZoneServerInfo = 30;
     */
    OP_ZoneServerInfo = 30,
    /**
     * @generated from protobuf enum value: OP_WebInitiateConnection = 31;
     */
    OP_WebInitiateConnection = 31,
    /**
     * Zone
     *
     * @generated from protobuf enum value: OP_ZoneSession = 32;
     */
    OP_ZoneSession = 32,
    /**
     * @generated from protobuf enum value: OP_ZoneSessionValid = 33;
     */
    OP_ZoneSessionValid = 33,
    /**
     * @generated from protobuf enum value: OP_ZoneEntry = 34;
     */
    OP_ZoneEntry = 34,
    /**
     * @generated from protobuf enum value: OP_SetServerFilter = 35;
     */
    OP_SetServerFilter = 35,
    /**
     * @generated from protobuf enum value: OP_SendAATable = 36;
     */
    OP_SendAATable = 36,
    /**
     * @generated from protobuf enum value: OP_SendTributes = 37;
     */
    OP_SendTributes = 37,
    /**
     * @generated from protobuf enum value: OP_SendGuildTributes = 38;
     */
    OP_SendGuildTributes = 38,
    /**
     * @generated from protobuf enum value: OP_SendAAStats = 39;
     */
    OP_SendAAStats = 39,
    /**
     * @generated from protobuf enum value: OP_ReqClientSpawn = 40;
     */
    OP_ReqClientSpawn = 40,
    /**
     * @generated from protobuf enum value: OP_ReqNewZone = 41;
     */
    OP_ReqNewZone = 41,
    /**
     * @generated from protobuf enum value: OP_SendExpZonein = 42;
     */
    OP_SendExpZonein = 42,
    /**
     * @generated from protobuf enum value: OP_ClientReady = 43;
     */
    OP_ClientReady = 43,
    /**
     * @generated from protobuf enum value: OP_ClientError = 44;
     */
    OP_ClientError = 44,
    /**
     * @generated from protobuf enum value: OP_ApproveZone = 45;
     */
    OP_ApproveZone = 45,
    /**
     * @generated from protobuf enum value: OP_TGB = 46;
     */
    OP_TGB = 46,
    /**
     * @generated from protobuf enum value: OP_AckPacket = 47;
     */
    OP_AckPacket = 47,
    /**
     * @generated from protobuf enum value: OP_ClientUpdate = 48;
     */
    OP_ClientUpdate = 48,
    /**
     * @generated from protobuf enum value: OP_AutoAttack = 49;
     */
    OP_AutoAttack = 49,
    /**
     * @generated from protobuf enum value: OP_AutoAttack2 = 50;
     */
    OP_AutoAttack2 = 50,
    /**
     * @generated from protobuf enum value: OP_Consent = 51;
     */
    OP_Consent = 51,
    /**
     * @generated from protobuf enum value: OP_ConsentDeny = 52;
     */
    OP_ConsentDeny = 52,
    /**
     * @generated from protobuf enum value: OP_TargetMouse = 53;
     */
    OP_TargetMouse = 53,
    /**
     * @generated from protobuf enum value: OP_TargetCommand = 54;
     */
    OP_TargetCommand = 54,
    /**
     * @generated from protobuf enum value: OP_Shielding = 55;
     */
    OP_Shielding = 55,
    /**
     * @generated from protobuf enum value: OP_Jump = 56;
     */
    OP_Jump = 56,
    /**
     * @generated from protobuf enum value: OP_AdventureInfoRequest = 57;
     */
    OP_AdventureInfoRequest = 57,
    /**
     * @generated from protobuf enum value: OP_AdventureRequest = 58;
     */
    OP_AdventureRequest = 58,
    /**
     * @generated from protobuf enum value: OP_LDoNButton = 59;
     */
    OP_LDoNButton = 59,
    /**
     * @generated from protobuf enum value: OP_LeaveAdventure = 60;
     */
    OP_LeaveAdventure = 60,
    /**
     * @generated from protobuf enum value: OP_Consume = 61;
     */
    OP_Consume = 61,
    /**
     * @generated from protobuf enum value: OP_AdventureMerchantRequest = 62;
     */
    OP_AdventureMerchantRequest = 62,
    /**
     * @generated from protobuf enum value: OP_AdventureMerchantPurchase = 63;
     */
    OP_AdventureMerchantPurchase = 63,
    /**
     * @generated from protobuf enum value: OP_ConsiderCorpse = 64;
     */
    OP_ConsiderCorpse = 64,
    /**
     * @generated from protobuf enum value: OP_Consider = 65;
     */
    OP_Consider = 65,
    /**
     * @generated from protobuf enum value: OP_Begging = 66;
     */
    OP_Begging = 66,
    /**
     * @generated from protobuf enum value: OP_TestBuff = 67;
     */
    OP_TestBuff = 67,
    /**
     * @generated from protobuf enum value: OP_Surname = 68;
     */
    OP_Surname = 68,
    /**
     * @generated from protobuf enum value: OP_YellForHelp = 69;
     */
    OP_YellForHelp = 69,
    /**
     * @generated from protobuf enum value: OP_Assist = 70;
     */
    OP_Assist = 70,
    /**
     * @generated from protobuf enum value: OP_GMTraining = 71;
     */
    OP_GMTraining = 71,
    /**
     * @generated from protobuf enum value: OP_GMEndTraining = 72;
     */
    OP_GMEndTraining = 72,
    /**
     * @generated from protobuf enum value: OP_GMTrainSkill = 73;
     */
    OP_GMTrainSkill = 73,
    /**
     * @generated from protobuf enum value: OP_RequestDuel = 74;
     */
    OP_RequestDuel = 74,
    /**
     * @generated from protobuf enum value: OP_DuelDecline = 75;
     */
    OP_DuelDecline = 75,
    /**
     * @generated from protobuf enum value: OP_DuelAccept = 76;
     */
    OP_DuelAccept = 76,
    /**
     * @generated from protobuf enum value: OP_SpawnAppearance = 77;
     */
    OP_SpawnAppearance = 77,
    /**
     * @generated from protobuf enum value: OP_BazaarInspect = 78;
     */
    OP_BazaarInspect = 78,
    /**
     * @generated from protobuf enum value: OP_Death = 79;
     */
    OP_Death = 79,
    /**
     * @generated from protobuf enum value: OP_MoveCoin = 80;
     */
    OP_MoveCoin = 80,
    /**
     * @generated from protobuf enum value: OP_ItemLinkClick = 81;
     */
    OP_ItemLinkClick = 81,
    /**
     * @generated from protobuf enum value: OP_MoveItem = 82;
     */
    OP_MoveItem = 82,
    /**
     * @generated from protobuf enum value: OP_Camp = 83;
     */
    OP_Camp = 83,
    /**
     * @generated from protobuf enum value: OP_Logout = 84;
     */
    OP_Logout = 84,
    /**
     * @generated from protobuf enum value: OP_SenseHeading = 85;
     */
    OP_SenseHeading = 85,
    /**
     * @generated from protobuf enum value: OP_FeignDeath = 86;
     */
    OP_FeignDeath = 86,
    /**
     * @generated from protobuf enum value: OP_Sneak = 87;
     */
    OP_Sneak = 87,
    /**
     * @generated from protobuf enum value: OP_Hide = 88;
     */
    OP_Hide = 88,
    /**
     * @generated from protobuf enum value: OP_ChannelMessage = 89;
     */
    OP_ChannelMessage = 89,
    /**
     * @generated from protobuf enum value: OP_WearChange = 90;
     */
    OP_WearChange = 90,
    /**
     * @generated from protobuf enum value: OP_DeleteSpawn = 91;
     */
    OP_DeleteSpawn = 91,
    /**
     * @generated from protobuf enum value: OP_SaveOnZoneReq = 92;
     */
    OP_SaveOnZoneReq = 92,
    /**
     * @generated from protobuf enum value: OP_Save = 93;
     */
    OP_Save = 93,
    /**
     * @generated from protobuf enum value: OP_WhoAllRequest = 94;
     */
    OP_WhoAllRequest = 94,
    /**
     * @generated from protobuf enum value: OP_GMZoneRequest = 95;
     */
    OP_GMZoneRequest = 95,
    /**
     * @generated from protobuf enum value: OP_GMZoneRequest2 = 96;
     */
    OP_GMZoneRequest2 = 96,
    /**
     * @generated from protobuf enum value: OP_EndLootRequest = 97;
     */
    OP_EndLootRequest = 97,
    /**
     * @generated from protobuf enum value: OP_LootRequest = 98;
     */
    OP_LootRequest = 98,
    /**
     * @generated from protobuf enum value: OP_Dye = 99;
     */
    OP_Dye = 99,
    /**
     * @generated from protobuf enum value: OP_ConfirmDelete = 100;
     */
    OP_ConfirmDelete = 100,
    /**
     * @generated from protobuf enum value: OP_LootItem = 101;
     */
    OP_LootItem = 101,
    /**
     * @generated from protobuf enum value: OP_GuildDelete = 102;
     */
    OP_GuildDelete = 102,
    /**
     * @generated from protobuf enum value: OP_GuildPublicNote = 103;
     */
    OP_GuildPublicNote = 103,
    /**
     * @generated from protobuf enum value: OP_GetGuildsList = 104;
     */
    OP_GetGuildsList = 104,
    /**
     * @generated from protobuf enum value: OP_SetGuildMOTD = 105;
     */
    OP_SetGuildMOTD = 105,
    /**
     * @generated from protobuf enum value: OP_SetRunMode = 106;
     */
    OP_SetRunMode = 106,
    /**
     * @generated from protobuf enum value: OP_GuildPeace = 107;
     */
    OP_GuildPeace = 107,
    /**
     * @generated from protobuf enum value: OP_GuildWar = 108;
     */
    OP_GuildWar = 108,
    /**
     * @generated from protobuf enum value: OP_GuildLeader = 109;
     */
    OP_GuildLeader = 109,
    /**
     * @generated from protobuf enum value: OP_GuildDemote = 110;
     */
    OP_GuildDemote = 110,
    /**
     * @generated from protobuf enum value: OP_GuildInvite = 111;
     */
    OP_GuildInvite = 111,
    /**
     * @generated from protobuf enum value: OP_GuildRemove = 112;
     */
    OP_GuildRemove = 112,
    /**
     * @generated from protobuf enum value: OP_GuildInviteAccept = 113;
     */
    OP_GuildInviteAccept = 113,
    /**
     * @generated from protobuf enum value: OP_ManaChange = 114;
     */
    OP_ManaChange = 114,
    /**
     * @generated from protobuf enum value: OP_MemorizeSpell = 115;
     */
    OP_MemorizeSpell = 115,
    /**
     * @generated from protobuf enum value: OP_SwapSpell = 116;
     */
    OP_SwapSpell = 116,
    /**
     * @generated from protobuf enum value: OP_CastSpell = 117;
     */
    OP_CastSpell = 117,
    /**
     * @generated from protobuf enum value: OP_DeleteItem = 118;
     */
    OP_DeleteItem = 118,
    /**
     * @generated from protobuf enum value: OP_CombatAbility = 119;
     */
    OP_CombatAbility = 119,
    /**
     * @generated from protobuf enum value: OP_Taunt = 120;
     */
    OP_Taunt = 120,
    /**
     * @generated from protobuf enum value: OP_InstillDoubt = 121;
     */
    OP_InstillDoubt = 121,
    /**
     * @generated from protobuf enum value: OP_RezzAnswer = 122;
     */
    OP_RezzAnswer = 122,
    /**
     * @generated from protobuf enum value: OP_GMSummon = 123;
     */
    OP_GMSummon = 123,
    /**
     * @generated from protobuf enum value: OP_TradeBusy = 124;
     */
    OP_TradeBusy = 124,
    /**
     * @generated from protobuf enum value: OP_TradeRequest = 125;
     */
    OP_TradeRequest = 125,
    /**
     * @generated from protobuf enum value: OP_TradeRequestAck = 126;
     */
    OP_TradeRequestAck = 126,
    /**
     * @generated from protobuf enum value: OP_CancelTrade = 127;
     */
    OP_CancelTrade = 127,
    /**
     * @generated from protobuf enum value: OP_TradeAcceptClick = 128;
     */
    OP_TradeAcceptClick = 128,
    /**
     * @generated from protobuf enum value: OP_BoardBoat = 129;
     */
    OP_BoardBoat = 129,
    /**
     * @generated from protobuf enum value: OP_LeaveBoat = 130;
     */
    OP_LeaveBoat = 130,
    /**
     * @generated from protobuf enum value: OP_RandomReq = 131;
     */
    OP_RandomReq = 131,
    /**
     * @generated from protobuf enum value: OP_Buff = 132;
     */
    OP_Buff = 132,
    /**
     * @generated from protobuf enum value: OP_GMHideMe = 133;
     */
    OP_GMHideMe = 133,
    /**
     * @generated from protobuf enum value: OP_GMNameChange = 134;
     */
    OP_GMNameChange = 134,
    /**
     * @generated from protobuf enum value: OP_GMKill = 135;
     */
    OP_GMKill = 135,
    /**
     * @generated from protobuf enum value: OP_GMLastName = 136;
     */
    OP_GMLastName = 136,
    /**
     * @generated from protobuf enum value: OP_GMToggle = 137;
     */
    OP_GMToggle = 137,
    /**
     * @generated from protobuf enum value: OP_LFGCommand = 138;
     */
    OP_LFGCommand = 138,
    /**
     * @generated from protobuf enum value: OP_GMGoto = 139;
     */
    OP_GMGoto = 139,
    /**
     * @generated from protobuf enum value: OP_TraderShop = 140;
     */
    OP_TraderShop = 140,
    /**
     * @generated from protobuf enum value: OP_ShopRequest = 141;
     */
    OP_ShopRequest = 141,
    /**
     * @generated from protobuf enum value: OP_Bazaar = 142;
     */
    OP_Bazaar = 142,
    /**
     * @generated from protobuf enum value: OP_ShopPlayerBuy = 143;
     */
    OP_ShopPlayerBuy = 143,
    /**
     * @generated from protobuf enum value: OP_ShopPlayerSell = 144;
     */
    OP_ShopPlayerSell = 144,
    /**
     * @generated from protobuf enum value: OP_ShopEnd = 145;
     */
    OP_ShopEnd = 145,
    /**
     * @generated from protobuf enum value: OP_CloseContainer = 146;
     */
    OP_CloseContainer = 146,
    /**
     * @generated from protobuf enum value: OP_ClickObjectAction = 147;
     */
    OP_ClickObjectAction = 147,
    /**
     * @generated from protobuf enum value: OP_ClickObject = 148;
     */
    OP_ClickObject = 148,
    /**
     * @generated from protobuf enum value: OP_RecipesFavorite = 149;
     */
    OP_RecipesFavorite = 149,
    /**
     * @generated from protobuf enum value: OP_RecipesSearch = 150;
     */
    OP_RecipesSearch = 150,
    /**
     * @generated from protobuf enum value: OP_RecipeDetails = 151;
     */
    OP_RecipeDetails = 151,
    /**
     * @generated from protobuf enum value: OP_RecipeAutoCombine = 152;
     */
    OP_RecipeAutoCombine = 152,
    /**
     * @generated from protobuf enum value: OP_TradeSkillCombine = 153;
     */
    OP_TradeSkillCombine = 153,
    /**
     * @generated from protobuf enum value: OP_ItemName = 154;
     */
    OP_ItemName = 154,
    /**
     * @generated from protobuf enum value: OP_AugmentItem = 155;
     */
    OP_AugmentItem = 155,
    /**
     * @generated from protobuf enum value: OP_ClickDoor = 156;
     */
    OP_ClickDoor = 156,
    /**
     * @generated from protobuf enum value: OP_FaceChange = 157;
     */
    OP_FaceChange = 157,
    /**
     * @generated from protobuf enum value: OP_GroupInvite = 158;
     */
    OP_GroupInvite = 158,
    /**
     * @generated from protobuf enum value: OP_GroupInvite2 = 159;
     */
    OP_GroupInvite2 = 159,
    /**
     * @generated from protobuf enum value: OP_GroupFollow = 160;
     */
    OP_GroupFollow = 160,
    /**
     * @generated from protobuf enum value: OP_GroupFollow2 = 161;
     */
    OP_GroupFollow2 = 161,
    /**
     * @generated from protobuf enum value: OP_GroupAcknowledge = 162;
     */
    OP_GroupAcknowledge = 162,
    /**
     * @generated from protobuf enum value: OP_GroupCancelInvite = 163;
     */
    OP_GroupCancelInvite = 163,
    /**
     * @generated from protobuf enum value: OP_GroupDisband = 164;
     */
    OP_GroupDisband = 164,
    /**
     * @generated from protobuf enum value: OP_GroupDelete = 165;
     */
    OP_GroupDelete = 165,
    /**
     * @generated from protobuf enum value: OP_GMEmoteZone = 166;
     */
    OP_GMEmoteZone = 166,
    /**
     * @generated from protobuf enum value: OP_InspectRequest = 167;
     */
    OP_InspectRequest = 167,
    /**
     * @generated from protobuf enum value: OP_InspectAnswer = 168;
     */
    OP_InspectAnswer = 168,
    /**
     * @generated from protobuf enum value: OP_DeleteSpell = 169;
     */
    OP_DeleteSpell = 169,
    /**
     * @generated from protobuf enum value: OP_PetitionBug = 170;
     */
    OP_PetitionBug = 170,
    /**
     * @generated from protobuf enum value: OP_Bug = 171;
     */
    OP_Bug = 171,
    /**
     * @generated from protobuf enum value: OP_Petition = 172;
     */
    OP_Petition = 172,
    /**
     * @generated from protobuf enum value: OP_PetitionCheckIn = 173;
     */
    OP_PetitionCheckIn = 173,
    /**
     * @generated from protobuf enum value: OP_PetitionResolve = 174;
     */
    OP_PetitionResolve = 174,
    /**
     * @generated from protobuf enum value: OP_PetitionDelete = 175;
     */
    OP_PetitionDelete = 175,
    /**
     * @generated from protobuf enum value: OP_PetitionUnCheckout = 176;
     */
    OP_PetitionUnCheckout = 176,
    /**
     * @generated from protobuf enum value: OP_PetitionQue = 177;
     */
    OP_PetitionQue = 177,
    /**
     * @generated from protobuf enum value: OP_PDeletePetition = 178;
     */
    OP_PDeletePetition = 178,
    /**
     * @generated from protobuf enum value: OP_PetitionCheckout = 179;
     */
    OP_PetitionCheckout = 179,
    /**
     * @generated from protobuf enum value: OP_PetitionRefresh = 180;
     */
    OP_PetitionRefresh = 180,
    /**
     * @generated from protobuf enum value: OP_PetCommands = 181;
     */
    OP_PetCommands = 181,
    /**
     * @generated from protobuf enum value: OP_ReadBook = 182;
     */
    OP_ReadBook = 182,
    /**
     * @generated from protobuf enum value: OP_Emote = 183;
     */
    OP_Emote = 183,
    /**
     * @generated from protobuf enum value: OP_GMDelCorpse = 184;
     */
    OP_GMDelCorpse = 184,
    /**
     * @generated from protobuf enum value: OP_GMKick = 185;
     */
    OP_GMKick = 185,
    /**
     * @generated from protobuf enum value: OP_GMServers = 186;
     */
    OP_GMServers = 186,
    /**
     * @generated from protobuf enum value: OP_Illusion = 187;
     */
    OP_Illusion = 187,
    /**
     * @generated from protobuf enum value: OP_GMBecomeNPC = 188;
     */
    OP_GMBecomeNPC = 188,
    /**
     * @generated from protobuf enum value: OP_Fishing = 189;
     */
    OP_Fishing = 189,
    /**
     * @generated from protobuf enum value: OP_Forage = 190;
     */
    OP_Forage = 190,
    /**
     * @generated from protobuf enum value: OP_Mend = 191;
     */
    OP_Mend = 191,
    /**
     * @generated from protobuf enum value: OP_EnvDamage = 192;
     */
    OP_EnvDamage = 192,
    /**
     * @generated from protobuf enum value: OP_Damage = 193;
     */
    OP_Damage = 193,
    /**
     * @generated from protobuf enum value: OP_AAAction = 194;
     */
    OP_AAAction = 194,
    /**
     * @generated from protobuf enum value: OP_TraderBuy = 195;
     */
    OP_TraderBuy = 195,
    /**
     * @generated from protobuf enum value: OP_Trader = 196;
     */
    OP_Trader = 196,
    /**
     * @generated from protobuf enum value: OP_GMFind = 197;
     */
    OP_GMFind = 197,
    /**
     * @generated from protobuf enum value: OP_PickPocket = 198;
     */
    OP_PickPocket = 198,
    /**
     * @generated from protobuf enum value: OP_Bind_Wound = 199;
     */
    OP_Bind_Wound = 199,
    /**
     * @generated from protobuf enum value: OP_TrackTarget = 200;
     */
    OP_TrackTarget = 200,
    /**
     * @generated from protobuf enum value: OP_Track = 201;
     */
    OP_Track = 201,
    /**
     * @generated from protobuf enum value: OP_TrackUnknown = 202;
     */
    OP_TrackUnknown = 202,
    /**
     * @generated from protobuf enum value: OP_ReloadUI = 203;
     */
    OP_ReloadUI = 203,
    /**
     * @generated from protobuf enum value: OP_Split = 204;
     */
    OP_Split = 204,
    /**
     * @generated from protobuf enum value: OP_SenseTraps = 205;
     */
    OP_SenseTraps = 205,
    /**
     * @generated from protobuf enum value: OP_DisarmTraps = 206;
     */
    OP_DisarmTraps = 206,
    /**
     * @generated from protobuf enum value: OP_OpenTributeMaster = 207;
     */
    OP_OpenTributeMaster = 207,
    /**
     * @generated from protobuf enum value: OP_OpenGuildTributeMaster = 208;
     */
    OP_OpenGuildTributeMaster = 208,
    /**
     * @generated from protobuf enum value: OP_TributeItem = 209;
     */
    OP_TributeItem = 209,
    /**
     * @generated from protobuf enum value: OP_TributeMoney = 210;
     */
    OP_TributeMoney = 210,
    /**
     * @generated from protobuf enum value: OP_SelectTribute = 211;
     */
    OP_SelectTribute = 211,
    /**
     * @generated from protobuf enum value: OP_TributeUpdate = 212;
     */
    OP_TributeUpdate = 212,
    /**
     * @generated from protobuf enum value: OP_TributeToggle = 213;
     */
    OP_TributeToggle = 213,
    /**
     * @generated from protobuf enum value: OP_TributeNPC = 214;
     */
    OP_TributeNPC = 214,
    /**
     * @generated from protobuf enum value: OP_CrashDump = 215;
     */
    OP_CrashDump = 215,
    /**
     * @generated from protobuf enum value: OP_ControlBoat = 216;
     */
    OP_ControlBoat = 216,
    /**
     * @generated from protobuf enum value: OP_DumpName = 217;
     */
    OP_DumpName = 217,
    /**
     * @generated from protobuf enum value: OP_SafeFallSuccess = 218;
     */
    OP_SafeFallSuccess = 218,
    /**
     * @generated from protobuf enum value: OP_Heartbeat = 219;
     */
    OP_Heartbeat = 219,
    /**
     * @generated from protobuf enum value: OP_SafePoint = 220;
     */
    OP_SafePoint = 220,
    /**
     * @generated from protobuf enum value: OP_FindPersonRequest = 221;
     */
    OP_FindPersonRequest = 221,
    /**
     * @generated from protobuf enum value: OP_LeadershipExpToggle = 222;
     */
    OP_LeadershipExpToggle = 222,
    /**
     * @generated from protobuf enum value: OP_PurchaseLeadershipAA = 223;
     */
    OP_PurchaseLeadershipAA = 223,
    /**
     * @generated from protobuf enum value: OP_BankerChange = 224;
     */
    OP_BankerChange = 224,
    /**
     * @generated from protobuf enum value: OP_SetTitle = 225;
     */
    OP_SetTitle = 225,
    /**
     * @generated from protobuf enum value: OP_RequestTitles = 226;
     */
    OP_RequestTitles = 226,
    /**
     * @generated from protobuf enum value: OP_ItemVerifyRequest = 227;
     */
    OP_ItemVerifyRequest = 227,
    /**
     * @generated from protobuf enum value: OP_ClearObject = 228;
     */
    OP_ClearObject = 228,
    /**
     * @generated from protobuf enum value: OP_FinishTrade = 229;
     */
    OP_FinishTrade = 229,
    /**
     * @generated from protobuf enum value: OP_GMEndTrainingResponse = 230;
     */
    OP_GMEndTrainingResponse = 230,
    /**
     * @generated from protobuf enum value: OP_LootComplete = 231;
     */
    OP_LootComplete = 231,
    /**
     * @generated from protobuf enum value: OP_WorldObjectsSent = 232;
     */
    OP_WorldObjectsSent = 232,
    /**
     * @generated from protobuf enum value: OP_FinishWindow = 233;
     */
    OP_FinishWindow = 233,
    /**
     * @generated from protobuf enum value: OP_FinishWindow2 = 234;
     */
    OP_FinishWindow2 = 234,
    /**
     * @generated from protobuf enum value: OP_ItemPacket = 235;
     */
    OP_ItemPacket = 235,
    /**
     * @generated from protobuf enum value: OP_ColoredText = 236;
     */
    OP_ColoredText = 236,
    /**
     * @generated from protobuf enum value: OP_ItemRecastDelay = 237;
     */
    OP_ItemRecastDelay = 237,
    /**
     * @generated from protobuf enum value: OP_FormattedMessage = 238;
     */
    OP_FormattedMessage = 238,
    /**
     * @generated from protobuf enum value: OP_GuildMemberList = 239;
     */
    OP_GuildMemberList = 239,
    /**
     * @generated from protobuf enum value: OP_InterruptCast = 240;
     */
    OP_InterruptCast = 240,
    /**
     * @generated from protobuf enum value: OP_ItemLinkResponse = 241;
     */
    OP_ItemLinkResponse = 241,
    /**
     * @generated from protobuf enum value: OP_ZoneSpawns = 242;
     */
    OP_ZoneSpawns = 242,
    /**
     * @generated from protobuf enum value: OP_CompletedTasks = 243;
     */
    OP_CompletedTasks = 243,
    /**
     * @generated from protobuf enum value: OP_CharInventory = 244;
     */
    OP_CharInventory = 244,
    /**
     * @generated from protobuf enum value: OP_CustomTitles = 245;
     */
    OP_CustomTitles = 245,
    /**
     * @generated from protobuf enum value: OP_SpawnDoor = 246;
     */
    OP_SpawnDoor = 246,
    /**
     * @generated from protobuf enum value: OP_SendZonepoints = 247;
     */
    OP_SendZonepoints = 247,
    /**
     * @generated from protobuf enum value: OP_TributeInfo = 248;
     */
    OP_TributeInfo = 248,
    /**
     * @generated from protobuf enum value: OP_GuildTributeInfo = 249;
     */
    OP_GuildTributeInfo = 249,
    /**
     * @generated from protobuf enum value: OP_SendTitleList = 250;
     */
    OP_SendTitleList = 250,
    /**
     * @generated from protobuf enum value: OP_AAExpUpdate = 251;
     */
    OP_AAExpUpdate = 251,
    /**
     * @generated from protobuf enum value: OP_Action = 252;
     */
    OP_Action = 252,
    /**
     * @generated from protobuf enum value: OP_AdventureData = 253;
     */
    OP_AdventureData = 253,
    /**
     * @generated from protobuf enum value: OP_AdventureFinish = 254;
     */
    OP_AdventureFinish = 254,
    /**
     * @generated from protobuf enum value: OP_AdventurePointsUpdate = 255;
     */
    OP_AdventurePointsUpdate = 255,
    /**
     * @generated from protobuf enum value: OP_Animation = 256;
     */
    OP_Animation = 256,
    /**
     * @generated from protobuf enum value: OP_AnnoyingZoneUnknown = 257;
     */
    OP_AnnoyingZoneUnknown = 257,
    /**
     * @generated from protobuf enum value: OP_BecomeTrader = 258;
     */
    OP_BecomeTrader = 258,
    /**
     * @generated from protobuf enum value: OP_BeginCast = 259;
     */
    OP_BeginCast = 259,
    /**
     * @generated from protobuf enum value: OP_Charm = 260;
     */
    OP_Charm = 260,
    /**
     * @generated from protobuf enum value: OP_CameraEffect = 261;
     */
    OP_CameraEffect = 261,
    /**
     * @generated from protobuf enum value: OP_ConsentResponse = 262;
     */
    OP_ConsentResponse = 262,
    /**
     * @generated from protobuf enum value: OP_EnduranceUpdate = 263;
     */
    OP_EnduranceUpdate = 263,
    /**
     * @generated from protobuf enum value: OP_ExpUpdate = 264;
     */
    OP_ExpUpdate = 264,
    /**
     * @generated from protobuf enum value: OP_GroundSpawn = 265;
     */
    OP_GroundSpawn = 265,
    /**
     * @generated from protobuf enum value: OP_GroupUpdate = 266;
     */
    OP_GroupUpdate = 266,
    /**
     * @generated from protobuf enum value: OP_GuildMOTD = 267;
     */
    OP_GuildMOTD = 267,
    /**
     * @generated from protobuf enum value: OP_GuildManageAdd = 268;
     */
    OP_GuildManageAdd = 268,
    /**
     * @generated from protobuf enum value: OP_GuildManageRemove = 269;
     */
    OP_GuildManageRemove = 269,
    /**
     * @generated from protobuf enum value: OP_GuildManageStatus = 270;
     */
    OP_GuildManageStatus = 270,
    /**
     * @generated from protobuf enum value: OP_GuildMemberUpdate = 271;
     */
    OP_GuildMemberUpdate = 271,
    /**
     * @generated from protobuf enum value: OP_HPUpdate = 272;
     */
    OP_HPUpdate = 272,
    /**
     * @generated from protobuf enum value: OP_IncreaseStats = 273;
     */
    OP_IncreaseStats = 273,
    /**
     * @generated from protobuf enum value: OP_ItemVerifyReply = 274;
     */
    OP_ItemVerifyReply = 274,
    /**
     * @generated from protobuf enum value: OP_LFGAppearance = 275;
     */
    OP_LFGAppearance = 275,
    /**
     * @generated from protobuf enum value: OP_LeadershipExpUpdate = 276;
     */
    OP_LeadershipExpUpdate = 276,
    /**
     * @generated from protobuf enum value: OP_LevelAppearance = 277;
     */
    OP_LevelAppearance = 277,
    /**
     * @generated from protobuf enum value: OP_LevelUpdate = 278;
     */
    OP_LevelUpdate = 278,
    /**
     * @generated from protobuf enum value: OP_ManaUpdate = 279;
     */
    OP_ManaUpdate = 279,
    /**
     * @generated from protobuf enum value: OP_MobEnduranceUpdate = 280;
     */
    OP_MobEnduranceUpdate = 280,
    /**
     * @generated from protobuf enum value: OP_MobHealth = 281;
     */
    OP_MobHealth = 281,
    /**
     * @generated from protobuf enum value: OP_MobManaUpdate = 282;
     */
    OP_MobManaUpdate = 282,
    /**
     * @generated from protobuf enum value: OP_MobRename = 283;
     */
    OP_MobRename = 283,
    /**
     * @generated from protobuf enum value: OP_MoneyOnCorpse = 284;
     */
    OP_MoneyOnCorpse = 284,
    /**
     * @generated from protobuf enum value: OP_MoneyUpdate = 285;
     */
    OP_MoneyUpdate = 285,
    /**
     * @generated from protobuf enum value: OP_MoveDoor = 286;
     */
    OP_MoveDoor = 286,
    /**
     * @generated from protobuf enum value: OP_NewSpawn = 287;
     */
    OP_NewSpawn = 287,
    /**
     * @generated from protobuf enum value: OP_NewZone = 288;
     */
    OP_NewZone = 288,
    /**
     * @generated from protobuf enum value: OP_PetitionUpdate = 289;
     */
    OP_PetitionUpdate = 289,
    /**
     * @generated from protobuf enum value: OP_PlayerProfile = 290;
     */
    OP_PlayerProfile = 290,
    /**
     * @generated from protobuf enum value: OP_RaidUpdate = 291;
     */
    OP_RaidUpdate = 291,
    /**
     * @generated from protobuf enum value: OP_RandomReply = 292;
     */
    OP_RandomReply = 292,
    /**
     * @generated from protobuf enum value: OP_RecipeReply = 293;
     */
    OP_RecipeReply = 293,
    /**
     * @generated from protobuf enum value: OP_RequestClientZoneChange = 294;
     */
    OP_RequestClientZoneChange = 294,
    /**
     * @generated from protobuf enum value: OP_RespondAA = 295;
     */
    OP_RespondAA = 295,
    /**
     * @generated from protobuf enum value: OP_RezzRequest = 296;
     */
    OP_RezzRequest = 296,
    /**
     * @generated from protobuf enum value: OP_SetTitleReply = 297;
     */
    OP_SetTitleReply = 297,
    /**
     * @generated from protobuf enum value: OP_ShopDelItem = 298;
     */
    OP_ShopDelItem = 298,
    /**
     * @generated from protobuf enum value: OP_SimpleMessage = 299;
     */
    OP_SimpleMessage = 299,
    /**
     * @generated from protobuf enum value: OP_SkillUpdate = 300;
     */
    OP_SkillUpdate = 300,
    /**
     * @generated from protobuf enum value: OP_SomeItemPacketMaybe = 301;
     */
    OP_SomeItemPacketMaybe = 301,
    /**
     * @generated from protobuf enum value: OP_SpellEffect = 302;
     */
    OP_SpellEffect = 302,
    /**
     * @generated from protobuf enum value: OP_Stamina = 303;
     */
    OP_Stamina = 303,
    /**
     * @generated from protobuf enum value: OP_Stun = 304;
     */
    OP_Stun = 304,
    /**
     * @generated from protobuf enum value: OP_TargetReject = 305;
     */
    OP_TargetReject = 305,
    /**
     * @generated from protobuf enum value: OP_TimeOfDay = 306;
     */
    OP_TimeOfDay = 306,
    /**
     * @generated from protobuf enum value: OP_TradeCoins = 307;
     */
    OP_TradeCoins = 307,
    /**
     * @generated from protobuf enum value: OP_TradeMoneyUpdate = 308;
     */
    OP_TradeMoneyUpdate = 308,
    /**
     * @generated from protobuf enum value: OP_TraderDelItem = 309;
     */
    OP_TraderDelItem = 309,
    /**
     * @generated from protobuf enum value: OP_TraderItemUpdate = 310;
     */
    OP_TraderItemUpdate = 310,
    /**
     * @generated from protobuf enum value: OP_TributeTimer = 311;
     */
    OP_TributeTimer = 311,
    /**
     * @generated from protobuf enum value: OP_UpdateLeadershipAA = 312;
     */
    OP_UpdateLeadershipAA = 312,
    /**
     * @generated from protobuf enum value: OP_Weather = 313;
     */
    OP_Weather = 313,
    /**
     * @generated from protobuf enum value: OP_ZoneChange = 314;
     */
    OP_ZoneChange = 314,
    /**
     * @generated from protobuf enum value: OP_ZoneInUnknown = 315;
     */
    OP_ZoneInUnknown = 315,
    /**
     * @generated from protobuf enum value: OP_AcceptNewTask = 316;
     */
    OP_AcceptNewTask = 316,
    /**
     * @generated from protobuf enum value: OP_AdventureInfo = 317;
     */
    OP_AdventureInfo = 317,
    /**
     * @generated from protobuf enum value: OP_ApplyPoison = 318;
     */
    OP_ApplyPoison = 318,
    /**
     * @generated from protobuf enum value: OP_ApproveWorld = 319;
     */
    OP_ApproveWorld = 319,
    /**
     * @generated from protobuf enum value: OP_Bandolier = 320;
     */
    OP_Bandolier = 320,
    /**
     * @generated from protobuf enum value: OP_BazaarSearch = 321;
     */
    OP_BazaarSearch = 321,
    /**
     * @generated from protobuf enum value: OP_BecomeCorpse = 322;
     */
    OP_BecomeCorpse = 322,
    /**
     * @generated from protobuf enum value: OP_CancelTask = 323;
     */
    OP_CancelTask = 323,
    /**
     * @generated from protobuf enum value: OP_Command = 324;
     */
    OP_Command = 324,
    /**
     * @generated from protobuf enum value: OP_DynamicWall = 325;
     */
    OP_DynamicWall = 325,
    /**
     * @generated from protobuf enum value: OP_LFGuild = 326;
     */
    OP_LFGuild = 326,
    /**
     * @generated from protobuf enum value: OP_LoadSpellSet = 327;
     */
    OP_LoadSpellSet = 327,
    /**
     * @generated from protobuf enum value: OP_LogServer = 328;
     */
    OP_LogServer = 328,
    /**
     * @generated from protobuf enum value: OP_MOTD = 329;
     */
    OP_MOTD = 329,
    /**
     * @generated from protobuf enum value: OP_OnLevelMessage = 330;
     */
    OP_OnLevelMessage = 330,
    /**
     * @generated from protobuf enum value: OP_PlayMP3 = 331;
     */
    OP_PlayMP3 = 331,
    /**
     * @generated from protobuf enum value: OP_PotionBelt = 332;
     */
    OP_PotionBelt = 332,
    /**
     * @generated from protobuf enum value: OP_PVPStats = 333;
     */
    OP_PVPStats = 333,
    /**
     * @generated from protobuf enum value: OP_Report = 334;
     */
    OP_Report = 334,
    /**
     * @generated from protobuf enum value: OP_SpecialMesg = 335;
     */
    OP_SpecialMesg = 335,
    /**
     * @generated from protobuf enum value: OP_TaskActivity = 336;
     */
    OP_TaskActivity = 336,
    /**
     * @generated from protobuf enum value: OP_TaskDescription = 337;
     */
    OP_TaskDescription = 337,
    /**
     * @generated from protobuf enum value: OP_ZoneUnavail = 338;
     */
    OP_ZoneUnavail = 338,
    /**
     * @generated from protobuf enum value: OP_ExploreUnknown = 339;
     */
    OP_ExploreUnknown = 339,
    /**
     * @generated from protobuf enum value: OP_0x0193 = 340;
     */
    OP_0x0193 = 340,
    /**
     * @generated from protobuf enum value: OP_0x0347 = 341;
     */
    OP_0x0347 = 341,
    /**
     * @generated from protobuf enum value: OP_Action2 = 342;
     */
    OP_Action2 = 342,
    /**
     * @generated from protobuf enum value: OP_AddNimbusEffect = 343;
     */
    OP_AddNimbusEffect = 343,
    /**
     * @generated from protobuf enum value: OP_AdventureDetails = 344;
     */
    OP_AdventureDetails = 344,
    /**
     * @generated from protobuf enum value: OP_AdventureLeaderboardReply = 345;
     */
    OP_AdventureLeaderboardReply = 345,
    /**
     * @generated from protobuf enum value: OP_AdventureLeaderboardRequest = 346;
     */
    OP_AdventureLeaderboardRequest = 346,
    /**
     * @generated from protobuf enum value: OP_AdventureMerchantResponse = 347;
     */
    OP_AdventureMerchantResponse = 347,
    /**
     * @generated from protobuf enum value: OP_AdventureMerchantSell = 348;
     */
    OP_AdventureMerchantSell = 348,
    /**
     * @generated from protobuf enum value: OP_AdventureStatsReply = 349;
     */
    OP_AdventureStatsReply = 349,
    /**
     * @generated from protobuf enum value: OP_AdventureStatsRequest = 350;
     */
    OP_AdventureStatsRequest = 350,
    /**
     * @generated from protobuf enum value: OP_AdventureUpdate = 351;
     */
    OP_AdventureUpdate = 351,
    /**
     * @generated from protobuf enum value: OP_AggroMeterLockTarget = 352;
     */
    OP_AggroMeterLockTarget = 352,
    /**
     * @generated from protobuf enum value: OP_AggroMeterTargetInfo = 353;
     */
    OP_AggroMeterTargetInfo = 353,
    /**
     * @generated from protobuf enum value: OP_AggroMeterUpdate = 354;
     */
    OP_AggroMeterUpdate = 354,
    /**
     * @generated from protobuf enum value: OP_AltCurrency = 355;
     */
    OP_AltCurrency = 355,
    /**
     * @generated from protobuf enum value: OP_AltCurrencyMerchantReply = 356;
     */
    OP_AltCurrencyMerchantReply = 356,
    /**
     * @generated from protobuf enum value: OP_AltCurrencyMerchantRequest = 357;
     */
    OP_AltCurrencyMerchantRequest = 357,
    /**
     * @generated from protobuf enum value: OP_AltCurrencyPurchase = 358;
     */
    OP_AltCurrencyPurchase = 358,
    /**
     * @generated from protobuf enum value: OP_AltCurrencyReclaim = 359;
     */
    OP_AltCurrencyReclaim = 359,
    /**
     * @generated from protobuf enum value: OP_AltCurrencySell = 360;
     */
    OP_AltCurrencySell = 360,
    /**
     * @generated from protobuf enum value: OP_AltCurrencySellSelection = 361;
     */
    OP_AltCurrencySellSelection = 361,
    /**
     * @generated from protobuf enum value: OP_AssistGroup = 362;
     */
    OP_AssistGroup = 362,
    /**
     * @generated from protobuf enum value: OP_AugmentInfo = 363;
     */
    OP_AugmentInfo = 363,
    /**
     * @generated from protobuf enum value: OP_AutoFire = 364;
     */
    OP_AutoFire = 364,
    /**
     * @generated from protobuf enum value: OP_Barter = 365;
     */
    OP_Barter = 365,
    /**
     * @generated from protobuf enum value: OP_BlockedBuffs = 366;
     */
    OP_BlockedBuffs = 366,
    /**
     * @generated from protobuf enum value: OP_BookButton = 367;
     */
    OP_BookButton = 367,
    /**
     * @generated from protobuf enum value: OP_BuffCreate = 368;
     */
    OP_BuffCreate = 368,
    /**
     * @generated from protobuf enum value: OP_BuffRemoveRequest = 369;
     */
    OP_BuffRemoveRequest = 369,
    /**
     * @generated from protobuf enum value: OP_CancelSneakHide = 370;
     */
    OP_CancelSneakHide = 370,
    /**
     * @generated from protobuf enum value: OP_CashReward = 371;
     */
    OP_CashReward = 371,
    /**
     * @generated from protobuf enum value: OP_ChangeSize = 372;
     */
    OP_ChangeSize = 372,
    /**
     * @generated from protobuf enum value: OP_CharacterCreateRequest = 373;
     */
    OP_CharacterCreateRequest = 373,
    /**
     * @generated from protobuf enum value: OP_ChatMessage = 374;
     */
    OP_ChatMessage = 374,
    /**
     * @generated from protobuf enum value: OP_ClearAA = 375;
     */
    OP_ClearAA = 375,
    /**
     * @generated from protobuf enum value: OP_ClearBlockedBuffs = 376;
     */
    OP_ClearBlockedBuffs = 376,
    /**
     * @generated from protobuf enum value: OP_ClearLeadershipAbilities = 377;
     */
    OP_ClearLeadershipAbilities = 377,
    /**
     * @generated from protobuf enum value: OP_ClearNPCMarks = 378;
     */
    OP_ClearNPCMarks = 378,
    /**
     * @generated from protobuf enum value: OP_ClearSurname = 379;
     */
    OP_ClearSurname = 379,
    /**
     * @generated from protobuf enum value: OP_ClientTimeStamp = 380;
     */
    OP_ClientTimeStamp = 380,
    /**
     * @generated from protobuf enum value: OP_CloseTributeMaster = 381;
     */
    OP_CloseTributeMaster = 381,
    /**
     * @generated from protobuf enum value: OP_CorpseDrag = 382;
     */
    OP_CorpseDrag = 382,
    /**
     * @generated from protobuf enum value: OP_CorpseDrop = 383;
     */
    OP_CorpseDrop = 383,
    /**
     * @generated from protobuf enum value: OP_CrystalCountUpdate = 384;
     */
    OP_CrystalCountUpdate = 384,
    /**
     * @generated from protobuf enum value: OP_CrystalCreate = 385;
     */
    OP_CrystalCreate = 385,
    /**
     * @generated from protobuf enum value: OP_CrystalReclaim = 386;
     */
    OP_CrystalReclaim = 386,
    /**
     * @generated from protobuf enum value: OP_DelegateAbility = 387;
     */
    OP_DelegateAbility = 387,
    /**
     * @generated from protobuf enum value: OP_DeleteCharge = 388;
     */
    OP_DeleteCharge = 388,
    /**
     * @generated from protobuf enum value: OP_DeletePetition = 389;
     */
    OP_DeletePetition = 389,
    /**
     * @generated from protobuf enum value: OP_DenyResponse = 390;
     */
    OP_DenyResponse = 390,
    /**
     * @generated from protobuf enum value: OP_Disarm = 391;
     */
    OP_Disarm = 391,
    /**
     * @generated from protobuf enum value: OP_DisciplineTimer = 392;
     */
    OP_DisciplineTimer = 392,
    /**
     * @generated from protobuf enum value: OP_DisciplineUpdate = 393;
     */
    OP_DisciplineUpdate = 393,
    /**
     * @generated from protobuf enum value: OP_DiscordMerchantInventory = 394;
     */
    OP_DiscordMerchantInventory = 394,
    /**
     * @generated from protobuf enum value: OP_DoGroupLeadershipAbility = 395;
     */
    OP_DoGroupLeadershipAbility = 395,
    /**
     * @generated from protobuf enum value: OP_DzAddPlayer = 396;
     */
    OP_DzAddPlayer = 396,
    /**
     * @generated from protobuf enum value: OP_DzChooseZone = 397;
     */
    OP_DzChooseZone = 397,
    /**
     * @generated from protobuf enum value: OP_DzChooseZoneReply = 398;
     */
    OP_DzChooseZoneReply = 398,
    /**
     * @generated from protobuf enum value: OP_DzCompass = 399;
     */
    OP_DzCompass = 399,
    /**
     * @generated from protobuf enum value: OP_DzExpeditionEndsWarning = 400;
     */
    OP_DzExpeditionEndsWarning = 400,
    /**
     * @generated from protobuf enum value: OP_DzExpeditionInfo = 401;
     */
    OP_DzExpeditionInfo = 401,
    /**
     * @generated from protobuf enum value: OP_DzExpeditionInvite = 402;
     */
    OP_DzExpeditionInvite = 402,
    /**
     * @generated from protobuf enum value: OP_DzExpeditionInviteResponse = 403;
     */
    OP_DzExpeditionInviteResponse = 403,
    /**
     * @generated from protobuf enum value: OP_DzExpeditionLockoutTimers = 404;
     */
    OP_DzExpeditionLockoutTimers = 404,
    /**
     * @generated from protobuf enum value: OP_DzListTimers = 405;
     */
    OP_DzListTimers = 405,
    /**
     * @generated from protobuf enum value: OP_DzMakeLeader = 406;
     */
    OP_DzMakeLeader = 406,
    /**
     * @generated from protobuf enum value: OP_DzMemberList = 407;
     */
    OP_DzMemberList = 407,
    /**
     * @generated from protobuf enum value: OP_DzMemberListName = 408;
     */
    OP_DzMemberListName = 408,
    /**
     * @generated from protobuf enum value: OP_DzMemberListStatus = 409;
     */
    OP_DzMemberListStatus = 409,
    /**
     * @generated from protobuf enum value: OP_DzPlayerList = 410;
     */
    OP_DzPlayerList = 410,
    /**
     * @generated from protobuf enum value: OP_DzQuit = 411;
     */
    OP_DzQuit = 411,
    /**
     * @generated from protobuf enum value: OP_DzRemovePlayer = 412;
     */
    OP_DzRemovePlayer = 412,
    /**
     * @generated from protobuf enum value: OP_DzSetLeaderName = 413;
     */
    OP_DzSetLeaderName = 413,
    /**
     * @generated from protobuf enum value: OP_DzSwapPlayer = 414;
     */
    OP_DzSwapPlayer = 414,
    /**
     * @generated from protobuf enum value: OP_EnterChat = 415;
     */
    OP_EnterChat = 415,
    /**
     * @generated from protobuf enum value: OP_Feedback = 416;
     */
    OP_Feedback = 416,
    /**
     * @generated from protobuf enum value: OP_FellowshipUpdate = 417;
     */
    OP_FellowshipUpdate = 417,
    /**
     * @generated from protobuf enum value: OP_FindPersonReply = 418;
     */
    OP_FindPersonReply = 418,
    /**
     * @generated from protobuf enum value: OP_Fling = 419;
     */
    OP_Fling = 419,
    /**
     * @generated from protobuf enum value: OP_FloatListThing = 420;
     */
    OP_FloatListThing = 420,
    /**
     * @generated from protobuf enum value: OP_ForceFindPerson = 421;
     */
    OP_ForceFindPerson = 421,
    /**
     * @generated from protobuf enum value: OP_FriendsWho = 422;
     */
    OP_FriendsWho = 422,
    /**
     * @generated from protobuf enum value: OP_GetGuildMOTD = 423;
     */
    OP_GetGuildMOTD = 423,
    /**
     * @generated from protobuf enum value: OP_GetGuildMOTDReply = 424;
     */
    OP_GetGuildMOTDReply = 424,
    /**
     * @generated from protobuf enum value: OP_GiveMoney = 425;
     */
    OP_GiveMoney = 425,
    /**
     * @generated from protobuf enum value: OP_GMApproval = 426;
     */
    OP_GMApproval = 426,
    /**
     * @generated from protobuf enum value: OP_GMTrainSkillConfirm = 427;
     */
    OP_GMTrainSkillConfirm = 427,
    /**
     * @generated from protobuf enum value: OP_GroupDisbandOther = 428;
     */
    OP_GroupDisbandOther = 428,
    /**
     * @generated from protobuf enum value: OP_GroupDisbandYou = 429;
     */
    OP_GroupDisbandYou = 429,
    /**
     * @generated from protobuf enum value: OP_GroupLeaderChange = 430;
     */
    OP_GroupLeaderChange = 430,
    /**
     * @generated from protobuf enum value: OP_GroupLeadershipAAUpdate = 431;
     */
    OP_GroupLeadershipAAUpdate = 431,
    /**
     * @generated from protobuf enum value: OP_GroupMakeLeader = 432;
     */
    OP_GroupMakeLeader = 432,
    /**
     * @generated from protobuf enum value: OP_GroupMentor = 433;
     */
    OP_GroupMentor = 433,
    /**
     * @generated from protobuf enum value: OP_GroupRoles = 434;
     */
    OP_GroupRoles = 434,
    /**
     * @generated from protobuf enum value: OP_GroupUpdateB = 435;
     */
    OP_GroupUpdateB = 435,
    /**
     * @generated from protobuf enum value: OP_GroupUpdateLeaderAA = 436;
     */
    OP_GroupUpdateLeaderAA = 436,
    /**
     * @generated from protobuf enum value: OP_GuildBank = 437;
     */
    OP_GuildBank = 437,
    /**
     * @generated from protobuf enum value: OP_GuildBankItemList = 438;
     */
    OP_GuildBankItemList = 438,
    /**
     * @generated from protobuf enum value: OP_GuildCreate = 439;
     */
    OP_GuildCreate = 439,
    /**
     * @generated from protobuf enum value: OP_GuildManageBanker = 440;
     */
    OP_GuildManageBanker = 440,
    /**
     * @generated from protobuf enum value: OP_GuildMemberLevelUpdate = 441;
     */
    OP_GuildMemberLevelUpdate = 441,
    /**
     * @generated from protobuf enum value: OP_GuildPromote = 442;
     */
    OP_GuildPromote = 442,
    /**
     * @generated from protobuf enum value: OP_GuildStatus = 443;
     */
    OP_GuildStatus = 443,
    /**
     * @generated from protobuf enum value: OP_GuildUpdateURLAndChannel = 444;
     */
    OP_GuildUpdateURLAndChannel = 444,
    /**
     * @generated from protobuf enum value: OP_HideCorpse = 445;
     */
    OP_HideCorpse = 445,
    /**
     * @generated from protobuf enum value: OP_InitialHPUpdate = 446;
     */
    OP_InitialHPUpdate = 446,
    /**
     * @generated from protobuf enum value: OP_InitialMobHealth = 447;
     */
    OP_InitialMobHealth = 447,
    /**
     * @generated from protobuf enum value: OP_InspectBuffs = 448;
     */
    OP_InspectBuffs = 448,
    /**
     * @generated from protobuf enum value: OP_InspectMessageUpdate = 449;
     */
    OP_InspectMessageUpdate = 449,
    /**
     * @generated from protobuf enum value: OP_ItemLinkText = 450;
     */
    OP_ItemLinkText = 450,
    /**
     * @generated from protobuf enum value: OP_ItemPreview = 451;
     */
    OP_ItemPreview = 451,
    /**
     * @generated from protobuf enum value: OP_ItemViewUnknown = 452;
     */
    OP_ItemViewUnknown = 452,
    /**
     * @generated from protobuf enum value: OP_KeyRing = 453;
     */
    OP_KeyRing = 453,
    /**
     * @generated from protobuf enum value: OP_KickPlayers = 454;
     */
    OP_KickPlayers = 454,
    /**
     * @generated from protobuf enum value: OP_KnowledgeBase = 455;
     */
    OP_KnowledgeBase = 455,
    /**
     * @generated from protobuf enum value: OP_LDoNDisarmTraps = 456;
     */
    OP_LDoNDisarmTraps = 456,
    /**
     * @generated from protobuf enum value: OP_LDoNInspect = 457;
     */
    OP_LDoNInspect = 457,
    /**
     * @generated from protobuf enum value: OP_LDoNOpen = 458;
     */
    OP_LDoNOpen = 458,
    /**
     * @generated from protobuf enum value: OP_LDoNPickLock = 459;
     */
    OP_LDoNPickLock = 459,
    /**
     * @generated from protobuf enum value: OP_LDoNSenseTraps = 460;
     */
    OP_LDoNSenseTraps = 460,
    /**
     * @generated from protobuf enum value: OP_LFGGetMatchesRequest = 461;
     */
    OP_LFGGetMatchesRequest = 461,
    /**
     * @generated from protobuf enum value: OP_LFGGetMatchesResponse = 462;
     */
    OP_LFGGetMatchesResponse = 462,
    /**
     * @generated from protobuf enum value: OP_LFGResponse = 463;
     */
    OP_LFGResponse = 463,
    /**
     * @generated from protobuf enum value: OP_LFPCommand = 464;
     */
    OP_LFPCommand = 464,
    /**
     * @generated from protobuf enum value: OP_LFPGetMatchesRequest = 465;
     */
    OP_LFPGetMatchesRequest = 465,
    /**
     * @generated from protobuf enum value: OP_LFPGetMatchesResponse = 466;
     */
    OP_LFPGetMatchesResponse = 466,
    /**
     * @generated from protobuf enum value: OP_LinkedReuse = 467;
     */
    OP_LinkedReuse = 467,
    /**
     * @generated from protobuf enum value: OP_LocInfo = 468;
     */
    OP_LocInfo = 468,
    /**
     * @generated from protobuf enum value: OP_LockoutTimerInfo = 469;
     */
    OP_LockoutTimerInfo = 469,
    /**
     * @generated from protobuf enum value: OP_Login = 470;
     */
    OP_Login = 470,
    /**
     * @generated from protobuf enum value: OP_LoginComplete = 471;
     */
    OP_LoginComplete = 471,
    /**
     * @generated from protobuf enum value: OP_LoginExpansionPacketData = 472;
     */
    OP_LoginExpansionPacketData = 472,
    /**
     * @generated from protobuf enum value: OP_LoginUnknown1 = 473;
     */
    OP_LoginUnknown1 = 473,
    /**
     * @generated from protobuf enum value: OP_LoginUnknown2 = 474;
     */
    OP_LoginUnknown2 = 474,
    /**
     * @generated from protobuf enum value: OP_LogoutReply = 475;
     */
    OP_LogoutReply = 475,
    /**
     * @generated from protobuf enum value: OP_MarkNPC = 476;
     */
    OP_MarkNPC = 476,
    /**
     * @generated from protobuf enum value: OP_MarkRaidNPC = 477;
     */
    OP_MarkRaidNPC = 477,
    /**
     * @generated from protobuf enum value: OP_Marquee = 478;
     */
    OP_Marquee = 478,
    /**
     * @generated from protobuf enum value: OP_MendHPUpdate = 479;
     */
    OP_MendHPUpdate = 479,
    /**
     * @generated from protobuf enum value: OP_MercenaryAssign = 480;
     */
    OP_MercenaryAssign = 480,
    /**
     * @generated from protobuf enum value: OP_MercenaryCommand = 481;
     */
    OP_MercenaryCommand = 481,
    /**
     * @generated from protobuf enum value: OP_MercenaryDataRequest = 482;
     */
    OP_MercenaryDataRequest = 482,
    /**
     * @generated from protobuf enum value: OP_MercenaryDataResponse = 483;
     */
    OP_MercenaryDataResponse = 483,
    /**
     * @generated from protobuf enum value: OP_MercenaryDataUpdate = 484;
     */
    OP_MercenaryDataUpdate = 484,
    /**
     * @generated from protobuf enum value: OP_MercenaryDataUpdateRequest = 485;
     */
    OP_MercenaryDataUpdateRequest = 485,
    /**
     * @generated from protobuf enum value: OP_MercenaryDismiss = 486;
     */
    OP_MercenaryDismiss = 486,
    /**
     * @generated from protobuf enum value: OP_MercenaryHire = 487;
     */
    OP_MercenaryHire = 487,
    /**
     * @generated from protobuf enum value: OP_MercenarySuspendRequest = 488;
     */
    OP_MercenarySuspendRequest = 488,
    /**
     * @generated from protobuf enum value: OP_MercenarySuspendResponse = 489;
     */
    OP_MercenarySuspendResponse = 489,
    /**
     * @generated from protobuf enum value: OP_MercenaryTimer = 490;
     */
    OP_MercenaryTimer = 490,
    /**
     * @generated from protobuf enum value: OP_MercenaryTimerRequest = 491;
     */
    OP_MercenaryTimerRequest = 491,
    /**
     * @generated from protobuf enum value: OP_MercenaryUnknown1 = 492;
     */
    OP_MercenaryUnknown1 = 492,
    /**
     * @generated from protobuf enum value: OP_MercenaryUnsuspendResponse = 493;
     */
    OP_MercenaryUnsuspendResponse = 493,
    /**
     * @generated from protobuf enum value: OP_MobUpdate = 494;
     */
    OP_MobUpdate = 494,
    /**
     * @generated from protobuf enum value: OP_MoveMultipleItems = 495;
     */
    OP_MoveMultipleItems = 495,
    /**
     * @generated from protobuf enum value: OP_MoveLogDisregard = 496;
     */
    OP_MoveLogDisregard = 496,
    /**
     * @generated from protobuf enum value: OP_MoveLogRequest = 497;
     */
    OP_MoveLogRequest = 497,
    /**
     * @generated from protobuf enum value: OP_MultiLineMsg = 498;
     */
    OP_MultiLineMsg = 498,
    /**
     * @generated from protobuf enum value: OP_NewTitlesAvailable = 499;
     */
    OP_NewTitlesAvailable = 499,
    /**
     * @generated from protobuf enum value: OP_OpenContainer = 500;
     */
    OP_OpenContainer = 500,
    /**
     * @generated from protobuf enum value: OP_OpenDiscordMerchant = 501;
     */
    OP_OpenDiscordMerchant = 501,
    /**
     * @generated from protobuf enum value: OP_OpenInventory = 502;
     */
    OP_OpenInventory = 502,
    /**
     * @generated from protobuf enum value: OP_PetBuffWindow = 503;
     */
    OP_PetBuffWindow = 503,
    /**
     * @generated from protobuf enum value: OP_PetCommandState = 504;
     */
    OP_PetCommandState = 504,
    /**
     * @generated from protobuf enum value: OP_PetHoTT = 505;
     */
    OP_PetHoTT = 505,
    /**
     * @generated from protobuf enum value: OP_PetitionCheckout2 = 506;
     */
    OP_PetitionCheckout2 = 506,
    /**
     * @generated from protobuf enum value: OP_PetitionSearch = 507;
     */
    OP_PetitionSearch = 507,
    /**
     * @generated from protobuf enum value: OP_PetitionSearchResults = 508;
     */
    OP_PetitionSearchResults = 508,
    /**
     * @generated from protobuf enum value: OP_PetitionSearchText = 509;
     */
    OP_PetitionSearchText = 509,
    /**
     * @generated from protobuf enum value: OP_PlayerStateAdd = 510;
     */
    OP_PlayerStateAdd = 510,
    /**
     * @generated from protobuf enum value: OP_PlayerStateRemove = 511;
     */
    OP_PlayerStateRemove = 511,
    /**
     * @generated from protobuf enum value: OP_Poll = 512;
     */
    OP_Poll = 512,
    /**
     * @generated from protobuf enum value: OP_PollResponse = 513;
     */
    OP_PollResponse = 513,
    /**
     * @generated from protobuf enum value: OP_PopupResponse = 514;
     */
    OP_PopupResponse = 514,
    /**
     * @generated from protobuf enum value: OP_PreLogoutReply = 515;
     */
    OP_PreLogoutReply = 515,
    /**
     * @generated from protobuf enum value: OP_PVPLeaderBoardDetailsReply = 516;
     */
    OP_PVPLeaderBoardDetailsReply = 516,
    /**
     * @generated from protobuf enum value: OP_PVPLeaderBoardDetailsRequest = 517;
     */
    OP_PVPLeaderBoardDetailsRequest = 517,
    /**
     * @generated from protobuf enum value: OP_PVPLeaderBoardReply = 518;
     */
    OP_PVPLeaderBoardReply = 518,
    /**
     * @generated from protobuf enum value: OP_PVPLeaderBoardRequest = 519;
     */
    OP_PVPLeaderBoardRequest = 519,
    /**
     * @generated from protobuf enum value: OP_QueryResponseThing = 520;
     */
    OP_QueryResponseThing = 520,
    /**
     * @generated from protobuf enum value: OP_QueryUCSServerStatus = 521;
     */
    OP_QueryUCSServerStatus = 521,
    /**
     * @generated from protobuf enum value: OP_RaidDelegateAbility = 522;
     */
    OP_RaidDelegateAbility = 522,
    /**
     * @generated from protobuf enum value: OP_RaidClearNPCMarks = 523;
     */
    OP_RaidClearNPCMarks = 523,
    /**
     * @generated from protobuf enum value: OP_RaidInvite = 524;
     */
    OP_RaidInvite = 524,
    /**
     * @generated from protobuf enum value: OP_RaidJoin = 525;
     */
    OP_RaidJoin = 525,
    /**
     * @generated from protobuf enum value: OP_RandomNameGenerator = 526;
     */
    OP_RandomNameGenerator = 526,
    /**
     * @generated from protobuf enum value: OP_ReclaimCrystals = 527;
     */
    OP_ReclaimCrystals = 527,
    /**
     * @generated from protobuf enum value: OP_RemoveAllDoors = 528;
     */
    OP_RemoveAllDoors = 528,
    /**
     * @generated from protobuf enum value: OP_RemoveBlockedBuffs = 529;
     */
    OP_RemoveBlockedBuffs = 529,
    /**
     * @generated from protobuf enum value: OP_RemoveNimbusEffect = 530;
     */
    OP_RemoveNimbusEffect = 530,
    /**
     * @generated from protobuf enum value: OP_RemoveTrap = 531;
     */
    OP_RemoveTrap = 531,
    /**
     * @generated from protobuf enum value: OP_RequestKnowledgeBase = 532;
     */
    OP_RequestKnowledgeBase = 532,
    /**
     * @generated from protobuf enum value: OP_RespawnWindow = 533;
     */
    OP_RespawnWindow = 533,
    /**
     * @generated from protobuf enum value: OP_RestState = 534;
     */
    OP_RestState = 534,
    /**
     * @generated from protobuf enum value: OP_Rewind = 535;
     */
    OP_Rewind = 535,
    /**
     * @generated from protobuf enum value: OP_RezzComplete = 536;
     */
    OP_RezzComplete = 536,
    /**
     * @generated from protobuf enum value: OP_Sacrifice = 537;
     */
    OP_Sacrifice = 537,
    /**
     * @generated from protobuf enum value: OP_SendFindableNPCs = 538;
     */
    OP_SendFindableNPCs = 538,
    /**
     * @generated from protobuf enum value: OP_SendSystemStats = 539;
     */
    OP_SendSystemStats = 539,
    /**
     * @generated from protobuf enum value: OP_SessionReady = 540;
     */
    OP_SessionReady = 540,
    /**
     * @generated from protobuf enum value: OP_SetChatServer = 541;
     */
    OP_SetChatServer = 541,
    /**
     * @generated from protobuf enum value: OP_SetChatServer2 = 542;
     */
    OP_SetChatServer2 = 542,
    /**
     * @generated from protobuf enum value: OP_SetFace = 543;
     */
    OP_SetFace = 543,
    /**
     * @generated from protobuf enum value: OP_SetGroupTarget = 544;
     */
    OP_SetGroupTarget = 544,
    /**
     * @generated from protobuf enum value: OP_SetGuildRank = 545;
     */
    OP_SetGuildRank = 545,
    /**
     * @generated from protobuf enum value: OP_SetStartCity = 546;
     */
    OP_SetStartCity = 546,
    /**
     * @generated from protobuf enum value: OP_SharedTaskMemberList = 547;
     */
    OP_SharedTaskMemberList = 547,
    /**
     * @generated from protobuf enum value: OP_SharedTaskAddPlayer = 548;
     */
    OP_SharedTaskAddPlayer = 548,
    /**
     * @generated from protobuf enum value: OP_SharedTaskRemovePlayer = 549;
     */
    OP_SharedTaskRemovePlayer = 549,
    /**
     * @generated from protobuf enum value: OP_SharedTaskMakeLeader = 550;
     */
    OP_SharedTaskMakeLeader = 550,
    /**
     * @generated from protobuf enum value: OP_SharedTaskMemberInvite = 551;
     */
    OP_SharedTaskMemberInvite = 551,
    /**
     * @generated from protobuf enum value: OP_SharedTaskInvite = 552;
     */
    OP_SharedTaskInvite = 552,
    /**
     * @generated from protobuf enum value: OP_SharedTaskInviteResponse = 553;
     */
    OP_SharedTaskInviteResponse = 553,
    /**
     * @generated from protobuf enum value: OP_SharedTaskAcceptNew = 554;
     */
    OP_SharedTaskAcceptNew = 554,
    /**
     * @generated from protobuf enum value: OP_SharedTaskMemberChange = 555;
     */
    OP_SharedTaskMemberChange = 555,
    /**
     * @generated from protobuf enum value: OP_SharedTaskPlayerList = 556;
     */
    OP_SharedTaskPlayerList = 556,
    /**
     * @generated from protobuf enum value: OP_SharedTaskSelectWindow = 557;
     */
    OP_SharedTaskSelectWindow = 557,
    /**
     * @generated from protobuf enum value: OP_SharedTaskQuit = 558;
     */
    OP_SharedTaskQuit = 558,
    /**
     * @generated from protobuf enum value: OP_TaskTimers = 559;
     */
    OP_TaskTimers = 559,
    /**
     * @generated from protobuf enum value: OP_ShopEndConfirm = 560;
     */
    OP_ShopEndConfirm = 560,
    /**
     * @generated from protobuf enum value: OP_ShopItem = 561;
     */
    OP_ShopItem = 561,
    /**
     * @generated from protobuf enum value: OP_Some3ByteHPUpdate = 562;
     */
    OP_Some3ByteHPUpdate = 562,
    /**
     * @generated from protobuf enum value: OP_Some6ByteHPUpdate = 563;
     */
    OP_Some6ByteHPUpdate = 563,
    /**
     * @generated from protobuf enum value: OP_Sound = 564;
     */
    OP_Sound = 564,
    /**
     * @generated from protobuf enum value: OP_SpawnPositionUpdate = 565;
     */
    OP_SpawnPositionUpdate = 565,
    /**
     * @generated from protobuf enum value: OP_TargetBuffs = 566;
     */
    OP_TargetBuffs = 566,
    /**
     * @generated from protobuf enum value: OP_TargetHoTT = 567;
     */
    OP_TargetHoTT = 567,
    /**
     * @generated from protobuf enum value: OP_TaskActivityComplete = 568;
     */
    OP_TaskActivityComplete = 568,
    /**
     * @generated from protobuf enum value: OP_TaskHistoryReply = 569;
     */
    OP_TaskHistoryReply = 569,
    /**
     * @generated from protobuf enum value: OP_TaskHistoryRequest = 570;
     */
    OP_TaskHistoryRequest = 570,
    /**
     * @generated from protobuf enum value: OP_TaskRequestTimer = 571;
     */
    OP_TaskRequestTimer = 571,
    /**
     * @generated from protobuf enum value: OP_TaskSelectWindow = 572;
     */
    OP_TaskSelectWindow = 572,
    /**
     * @generated from protobuf enum value: OP_Translocate = 573;
     */
    OP_Translocate = 573,
    /**
     * @generated from protobuf enum value: OP_TributePointUpdate = 574;
     */
    OP_TributePointUpdate = 574,
    /**
     * @generated from protobuf enum value: OP_Untargetable = 575;
     */
    OP_Untargetable = 575,
    /**
     * @generated from protobuf enum value: OP_UpdateAA = 576;
     */
    OP_UpdateAA = 576,
    /**
     * @generated from protobuf enum value: OP_UpdateAura = 577;
     */
    OP_UpdateAura = 577,
    /**
     * @generated from protobuf enum value: OP_VetClaimReply = 578;
     */
    OP_VetClaimReply = 578,
    /**
     * @generated from protobuf enum value: OP_VetClaimRequest = 579;
     */
    OP_VetClaimRequest = 579,
    /**
     * @generated from protobuf enum value: OP_VetRewardsAvaliable = 580;
     */
    OP_VetRewardsAvaliable = 580,
    /**
     * @generated from protobuf enum value: OP_VoiceMacroIn = 581;
     */
    OP_VoiceMacroIn = 581,
    /**
     * @generated from protobuf enum value: OP_VoiceMacroOut = 582;
     */
    OP_VoiceMacroOut = 582,
    /**
     * @generated from protobuf enum value: OP_WeaponEquip1 = 583;
     */
    OP_WeaponEquip1 = 583,
    /**
     * @generated from protobuf enum value: OP_Weblink = 584;
     */
    OP_Weblink = 584,
    /**
     * @generated from protobuf enum value: OP_WhoAllResponse = 585;
     */
    OP_WhoAllResponse = 585,
    /**
     * @generated from protobuf enum value: OP_World_Client_CRC1 = 586;
     */
    OP_World_Client_CRC1 = 586,
    /**
     * @generated from protobuf enum value: OP_World_Client_CRC2 = 587;
     */
    OP_World_Client_CRC2 = 587,
    /**
     * @generated from protobuf enum value: OP_World_Client_CRC3 = 588;
     */
    OP_World_Client_CRC3 = 588,
    /**
     * @generated from protobuf enum value: OP_WorldClientReady = 589;
     */
    OP_WorldClientReady = 589,
    /**
     * @generated from protobuf enum value: OP_WorldComplete = 590;
     */
    OP_WorldComplete = 590,
    /**
     * @generated from protobuf enum value: OP_WorldLogout = 591;
     */
    OP_WorldLogout = 591,
    /**
     * @generated from protobuf enum value: OP_WorldUnknown001 = 592;
     */
    OP_WorldUnknown001 = 592,
    /**
     * @generated from protobuf enum value: OP_XTargetAutoAddHaters = 593;
     */
    OP_XTargetAutoAddHaters = 593,
    /**
     * @generated from protobuf enum value: OP_XTargetOpen = 594;
     */
    OP_XTargetOpen = 594,
    /**
     * @generated from protobuf enum value: OP_XTargetOpenResponse = 595;
     */
    OP_XTargetOpenResponse = 595,
    /**
     * @generated from protobuf enum value: OP_XTargetRequest = 596;
     */
    OP_XTargetRequest = 596,
    /**
     * @generated from protobuf enum value: OP_XTargetResponse = 597;
     */
    OP_XTargetResponse = 597,
    /**
     * @generated from protobuf enum value: OP_ZoneComplete = 598;
     */
    OP_ZoneComplete = 598,
    /**
     * @generated from protobuf enum value: OP_ZoneGuildList = 599;
     */
    OP_ZoneGuildList = 599,
    /**
     * @generated from protobuf enum value: OP_ZonePlayerToBind = 600;
     */
    OP_ZonePlayerToBind = 600,
    /**
     * @generated from protobuf enum value: OP_ZoneServerReady = 601;
     */
    OP_ZoneServerReady = 601,
    /**
     * @generated from protobuf enum value: OP_ResetAA = 602;
     */
    OP_ResetAA = 602,
    /**
     * @generated from protobuf enum value: OP_UnderWorld = 603;
     */
    OP_UnderWorld = 603,
    /**
     * World
     *
     * @generated from protobuf enum value: Nested_WorldServer = 1000;
     */
    Nested_WorldServer = 1000,
    /**
     * @generated from protobuf enum value: Nested_CharacterSelectEntry = 1001;
     */
    Nested_CharacterSelectEntry = 1001,
    /**
     * @generated from protobuf enum value: Nested_CharSelectEquip = 1002;
     */
    Nested_CharSelectEquip = 1002,
    /**
     * @generated from protobuf enum value: Nested_Tint = 1003;
     */
    Nested_Tint = 1003,
    /**
     * @generated from protobuf enum value: Nested_StringList = 1004;
     */
    Nested_StringList = 1004
}
