import * as core from "@babylonjs/core";
type CoreAPI = typeof import("@babylonjs/core");
type LoaderAPI = typeof import("@babylonjs/loaders/glTF/2.0");
declare const featureLoaders: {
    readonly babylon: () => Promise<typeof import("@babylonjs/core/Loading/Plugins/babylonFileLoader.pure.js")>;
    readonly gltf: () => Promise<typeof import("@babylonjs/loaders/glTF")>;
    readonly physics: () => Promise<{
        PhysicsEngineSceneComponent: typeof import("@babylonjs/core/Physics/joinedPhysicsEngineComponent.pure.js").PhysicsEngineSceneComponent;
        RegisterJoinedPhysicsEngineComponent(): void;
        RegisterPhysicsV2PhysicsEngineComponent(): void;
    }>;
    readonly gradientMaterial: () => Promise<typeof import("@babylonjs/materials/gradient/gradientMaterial")>;
    readonly serializers: () => Promise<typeof import("@babylonjs/serializers")>;
    readonly inspector: () => Promise<{
        BoundProperty: <TargetT extends object, PropertyKeyT extends keyof TargetT, ComponentT extends import("react").ComponentType<any>>(props: import("@babylonjs/inspector").BoundPropertyProps<TargetT, PropertyKeyT, ComponentT>, ref?: any) => import("react/jsx-runtime").JSX.Element | null;
        Property: <ComponentT extends import("react").ComponentType<any>>(props: import("@babylonjs/inspector").PropertyProps<ComponentT>, ref?: any) => import("react/jsx-runtime").JSX.Element;
        SceneContextIdentity: typeof import("@babylonjs/inspector").SceneContextIdentity;
        SelectionServiceIdentity: typeof import("@babylonjs/inspector").SelectionServiceIdentity;
        SelectionServiceDefinition: ServiceDefinition<[import("@babylonjs/inspector").ISelectionService], [IShellService, ISettingsStore, ISettingsService, import("@babylonjs/inspector").ISceneContext]>;
        LinkToEntity: import("react").FunctionComponent<import("@babylonjs/inspector").LinkToEntityProps>;
        LinkToEntityPropertyLine: import("react").FunctionComponent<PropertyLineProps<string> & import("@babylonjs/inspector").LinkToEntityProps>;
        PropertyContext: import("react").Context<import("@babylonjs/inspector").PropertyContext | undefined>;
        usePropertyChangedNotifier(): <ObjectT, PropertyT extends keyof ObjectT>(entity: ObjectT, propertyKey: PropertyT, oldValue: ObjectT[PropertyT], newValue: ObjectT[PropertyT]) => void;
        useProperty<TargetT extends object, PropertyKeyT extends keyof TargetT>(target: TargetT, propertyKey: PropertyKeyT): TargetT[PropertyKeyT];
        useProperty<TargetT extends object, PropertyKeyT extends keyof TargetT>(target: TargetT | null | undefined, propertyKey: PropertyKeyT): TargetT[PropertyKeyT] | undefined;
        useVector3Property<TargetT extends object, PropertyKeyT extends { [PropertyKeyT_1 in keyof TargetT]: TargetT[PropertyKeyT_1] extends core.Vector3 | null | undefined ? PropertyKeyT_1 : never; }[keyof TargetT]>(target: TargetT, propertyKey: PropertyKeyT): TargetT[PropertyKeyT];
        useVector3Property<TargetT extends object, PropertyKeyT extends { [PropertyKeyT_1 in keyof TargetT]: TargetT[PropertyKeyT_1] extends core.Vector3 | null | undefined ? PropertyKeyT_1 : never; }[keyof TargetT]>(target: TargetT | null | undefined, propertyKey: PropertyKeyT): TargetT[PropertyKeyT] | undefined;
        useColor3Property<TargetT extends object, PropertyKeyT extends { [PropertyKeyT_1 in keyof TargetT]: TargetT[PropertyKeyT_1] extends core.Color3 | null | undefined ? PropertyKeyT_1 : never; }[keyof TargetT]>(target: TargetT, propertyKey: PropertyKeyT): TargetT[PropertyKeyT];
        useColor3Property<TargetT extends object, PropertyKeyT extends { [PropertyKeyT_1 in keyof TargetT]: TargetT[PropertyKeyT_1] extends core.Color3 | null | undefined ? PropertyKeyT_1 : never; }[keyof TargetT]>(target: TargetT | null | undefined, propertyKey: PropertyKeyT): TargetT[PropertyKeyT] | undefined;
        useColor4Property<TargetT extends object, PropertyKeyT extends { [PropertyKeyT_1 in keyof TargetT]: TargetT[PropertyKeyT_1] extends core.Color4 | null | undefined ? PropertyKeyT_1 : never; }[keyof TargetT]>(target: TargetT, propertyKey: PropertyKeyT): TargetT[PropertyKeyT];
        useColor4Property<TargetT extends object, PropertyKeyT extends { [PropertyKeyT_1 in keyof TargetT]: TargetT[PropertyKeyT_1] extends core.Color4 | null | undefined ? PropertyKeyT_1 : never; }[keyof TargetT]>(target: TargetT | null | undefined, propertyKey: PropertyKeyT): TargetT[PropertyKeyT] | null;
        useQuaternionProperty<TargetT extends object, PropertyKeyT extends { [PropertyKeyT_1 in keyof TargetT]: TargetT[PropertyKeyT_1] extends core.Quaternion | null | undefined ? PropertyKeyT_1 : never; }[keyof TargetT]>(target: TargetT, propertyKey: PropertyKeyT): TargetT[PropertyKeyT];
        useQuaternionProperty<TargetT extends object, PropertyKeyT extends { [PropertyKeyT_1 in keyof TargetT]: TargetT[PropertyKeyT_1] extends core.Quaternion | null | undefined ? PropertyKeyT_1 : never; }[keyof TargetT]>(target: TargetT | null | undefined, propertyKey: PropertyKeyT): TargetT[PropertyKeyT] | undefined;
        MakePropertyHook(value: unknown): typeof import("@babylonjs/inspector").useProperty;
        useInterceptObservable<T extends object>(type: "function" | "property", target: T | null | undefined, propertyKey: keyof T): core.IReadonlyObservable<void>;
        usePollingObservable(delay: number): core.IReadonlyObservable<void>;
        useAngleConverters(): readonly [(angle: number, wrap?: boolean) => number, (angle: number, wrap?: boolean) => number, boolean];
        InterceptFunction<T extends object, K extends keyof T>(target: T, propertyKey: string extends K ? never : number extends K ? never : symbol extends K ? never : K, hooks: NonNullable<T[K]> extends (...args: infer Args) => unknown ? import("@babylonjs/inspector").FunctionHooks<Args> : import("@babylonjs/inspector").FunctionHooks): core.IDisposable;
        InterceptFunction<T extends object>(target: T, propertyKey: keyof T, hooks: import("@babylonjs/inspector").FunctionHooks): core.IDisposable;
        GetPropertyDescriptor<T extends object>(target: T, propertyKey: keyof T): core.Nullable<[owner: object, descriptor: PropertyDescriptor]>;
        IsPropertyReadonly(propertyDescriptor: PropertyDescriptor): boolean;
        InterceptProperty<T extends object, K extends keyof T>(target: T, propertyKey: string extends K ? never : number extends K ? never : symbol extends K ? never : K, hooks: import("@babylonjs/inspector").PropertyHooks<NonNullable<T[K]>>): core.IDisposable;
        InterceptProperty<T extends object>(target: T, propertyKey: keyof T, hooks: import("@babylonjs/inspector").PropertyHooks): core.IDisposable;
        ShowInspector(scene: core.Scene, options?: Partial<import("@babylonjs/inspector").InspectorOptions>): import("@babylonjs/inspector").InspectorToken;
        SidePaneContainer: any;
        PropertiesServiceIdentity: typeof import("@babylonjs/inspector").PropertiesServiceIdentity;
        SceneExplorerServiceIdentity: typeof import("@babylonjs/inspector").SceneExplorerServiceIdentity;
        DebugServiceIdentity: typeof import("@babylonjs/inspector").DebugServiceIdentity;
        SettingsServiceIdentity: any;
        StatsServiceIdentity: typeof import("@babylonjs/inspector").StatsServiceIdentity;
        ToolsServiceIdentity: typeof import("@babylonjs/inspector").ToolsServiceIdentity;
        ThemeServiceIdentity: any;
        SettingsStoreIdentity: any;
        GizmoServiceIdentity: typeof import("@babylonjs/inspector").GizmoServiceIdentity;
        WatcherServiceIdentity: typeof import("@babylonjs/inspector").WatcherServiceIdentity;
        inspectorAssetNotFoundHandler: typeof import("@babylonjs/inspector").inspectorAssetNotFoundHandler;
        ShellServiceIdentity: any;
        MakeModularTool: any;
        StartInspectable: typeof import("@babylonjs/inspector").StartInspectable;
        BridgeCommandRegistryIdentity: any;
        MakeModularBridge: any;
        ConvertOptions: typeof import("@babylonjs/inspector").ConvertOptions;
        Inspector: typeof import("@babylonjs/inspector").Inspector;
        AttachDebugLayer: typeof import("@babylonjs/inspector").AttachDebugLayer;
        DetachDebugLayer: typeof import("@babylonjs/inspector").DetachDebugLayer;
        NumberDropdownPropertyLine: any;
        StringDropdownPropertyLine: any;
        default: typeof import("@babylonjs/inspector");
    }>;
};
export type BabylonFeature = keyof typeof featureLoaders;
export type BabylonFeatureModule<K extends BabylonFeature> = Awaited<ReturnType<(typeof featureLoaders)[K]>>;
export type BabylonAPI = CoreAPI & LoaderAPI & {
    initialize(): Promise<void>;
    loadBabylonAssetContainer(bytes: ArrayBuffer, scene: CoreAPI["Scene"]["prototype"], options?: {
        name?: string;
        rootUrl?: string;
    }): Promise<CoreAPI["AssetContainer"]["prototype"]>;
    loadFeature<K extends BabylonFeature>(feature: K): Promise<BabylonFeatureModule<K>>;
    supportsFeature(feature: string): feature is BabylonFeature;
};
declare const exportObject: BabylonAPI;
export default exportObject;
