import type * as BJS from "@babylonjs/core";
import { PlayerProfile } from "@game/Net/messages";
import { NewZone, RequestClientZoneChange } from "@game/Net/messages";
import { ZonePacketHandler } from "@game/Net/zone-packets";
import { ZoneManager } from "@game/Zone/zone-manager";
import Player from "../Player/player";
import CharacterSelect from "../Zone/character-select";
export default class GameManager {
    engine: (BJS.Engine | BJS.WebGPUEngine | BJS.ThinEngine) | null;
    engineInitialized: boolean;
    canvas: HTMLCanvasElement | null;
    loadingRefCount: number;
    scene: BJS.Scene | null;
    private lastPlayer;
    player: Player | null;
    zonePacketHandler: ZonePacketHandler;
    havokPlugin: BJS.HavokPlugin | null;
    CurrentZone: NewZone | null;
    get CharacterSelect(): CharacterSelect | null;
    private characterSelect;
    get ZoneManager(): ZoneManager | null;
    private zoneManager;
    private camera;
    get Camera(): BJS.UniversalCamera | null;
    private secondaryCamera;
    get SecondaryCamera(): BJS.UniversalCamera | null;
    private static _instance;
    static get instance(): GameManager;
    constructor();
    initializeSecondaryCamera(): void;
    removeSecondaryCamera(): void;
    setInventoryViewport(x: number, y: number, width: number, height: number): void;
    setNewViewport(x: number, y: number, width: number, height: number): void;
    requestZone(requestZone: RequestClientZoneChange): void;
    loadPhysicsEngine(): Promise<boolean>;
    private pickingList;
    private pickListTimeout;
    addToPickingList(mesh: BJS.AbstractMesh): void;
    clearPickingList(): void;
    getPickingList(): BJS.AbstractMesh[];
    private refreshPickingList;
    gpuPicker: BJS.GPUPicker | null;
    loadEngine(canvas: any): Promise<void>;
    resize(): void;
    renderLoop(): void;
    private inspector;
    private instantiatingInspector;
    modifierKeys: {
        ctrl: boolean;
        shift: boolean;
        alt: boolean;
        meta: boolean;
    };
    keyUp(e: BJS.IKeyboardEvent): Promise<void>;
    keyDown(e: BJS.IKeyboardEvent): Promise<void>;
    setLoading(value: boolean): void;
    dispose(): void;
    loadCharacterSelect(): Promise<void>;
    loadZoneServer(zone: NewZone): Promise<void>;
    completeZoneLoad(): void;
    loadZoneId(zoneId: number): Promise<void>;
    loadZone(zoneName: string): Promise<void>;
    instantiatePlayer(player?: Partial<PlayerProfile> | null): Promise<void>;
}
